MAPS.push({
id:"ashes", slug:"ashes-of-the-damned", name:"Ashes of the Damned", color:"#d4622a", season:"Launch map", date:"Nov 14, 2025",
blurb:"The biggest map in the game: six hubs joined by fog roads full of super-sprinters. You get around in Ol' Tessie, the upgradeable car that also carries Pack-a-Punch.",
ww:"Necrofluid Gauntlet", boss:"Veytharion", reward:"Main Quest calling card",
mapImg: MGMAP("ashes-of-the-damned"),

wwInfo:{ what:"A gauntlet that fires a spike, then pulls it back when you reload (alt-fire). Anything the spike sticks in gets yanked toward you, which is how you grab the keys, teddies and clock energy later. Reloading also refills its ammo. Pack-a-Punched, the spikes can be detonated for area damage and still return the ammo.",
 steps:[
 {t:"Turn on power at the three hubs",loc:"Ashwood · Blackwater Lake · Vandorn Farm",b:["Shoot the orange growth off each hub's power pump, then flip the switch inside that hub's barn or cabin.","You only need this at step 5, but do it now while you wait for round 8."],q:["a1"]},
 {t:"Spawn and kill Uber Klaus → Stabilizer Chip",loc:"Janus Towers Plaza · wreckage right of the Blackwater Lake door",gate:"Round 8+",b:["Walk up to the burning wreckage to spawn Uber Klaus. Bring a Pack-a-Punched weapon.","Kill both of his phases. He drops the Stabilizer Chip."],ph:[["Wreckage that spawns him",MKP("ashes_of_the_damned","necrofluid_gauntlet/wreckage"),MKQ("ashes_of_the_damned")],["Stabilizer Chip",MKP("ashes_of_the_damned","necrofluid_gauntlet/stabilizer_chip"),MKQ("ashes_of_the_damned")]],q:["a8"]},
 {t:"Install the chip and stun Klaus free",loc:"Ashwood · Sheriff's Office (left of Vulture Aid)",b:["Interact with the panel on Klaus' cell to install the chip.","When it reads “Update requires restart”, quickly land <b>two Stun Grenades</b> on Klaus. A spinning-star icon over his head means it worked; he breaks out and follows you, killing zombies and reviving players.","Your tactical becomes the Klaus Remote, which sends him to a spot. When he goes on cooldown, call him back from any radio for 2,000."],
  spots:[{h:"Free Stun Grenades · both always spawn",list:[["Server Room in spawn (where you get T.E.D.D.'s Head)",MKP("ashes_of_the_damned","necrofluid_gauntlet/stun_grenade_server_room"),MKQ("ashes_of_the_damned")],["Shelf across from Juggernog in the Ruby Rabbit",MKP("ashes_of_the_damned","necrofluid_gauntlet/stun_grenade_jug"),MKQ("ashes_of_the_damned")]]}],
  ph:[["Cell panel",MKP("ashes_of_the_damned","necrofluid_gauntlet/klaus_panel"),MKQ("ashes_of_the_damned")]],q:["a9"]},
 {t:"Klaus' scan → Aether Canister",loc:"Zarya Cosmodrome · Support Systems",b:["<b>Drive</b> Ol' Tessie there. A jump pad would strand you without the car for the next step.","Command Klaus to the panel; he stomps and it lights up. Interact to start the scanner, then stand in the red circle until the bar on the left fills. A zombie in the circle pauses it; if you fail, retry next round.","Take the canister left of the panel. You can't sprint with it, and a jump pad makes you drop it."],
  ph:[["Panel for Klaus",MKP("ashes_of_the_damned","necrofluid_gauntlet/canister_panel"),MKQ("ashes_of_the_damned")],["Scanner circle",MKP("ashes_of_the_damned","necrofluid_gauntlet/scanner"),MKQ("ashes_of_the_damned")],["Canister",MKP("ashes_of_the_damned","necrofluid_gauntlet/canister"),MKQ("ashes_of_the_damned")]],q:["a10"]},
 {t:"Charge the canister at all three pumps",b:["Interact with each pump and wait for the canister to fill, then pick it up. Once it holds energy, a timer runs until the next pump, so drive.","Order used here: Ashwood → Blackwater Lake → Vandorn Farm (ends right next to the cube)."],
  spots:[{h:"Power pumps · use all three",list:[["1 · Ashwood",MKP("ashes_of_the_damned","necrofluid_gauntlet/power_pump_ashwood"),MKQ("ashes_of_the_damned")],["2 · Blackwater Lake",MKP("ashes_of_the_damned","necrofluid_gauntlet/power_pump_lake"),MKQ("ashes_of_the_damned")],["3 · Vandorn Farm",MKP("ashes_of_the_damned","necrofluid_gauntlet/power_pump_vandorn"),MKQ("ashes_of_the_damned")]]}],q:["a11"]},
 {t:"Feed the cube, then read the rooftop glyphs",loc:"Vandorn Farm cellar (under the barn) · Janus ↔ Vandorn jump pad",b:["Carry the charged canister up to the cube; it takes the energy and the canister disappears.","Ride the jump pad between Vandorn Farm and Janus Towers. Mid-air, read the three red symbols on the <b>Barn</b>, <b>House</b> and <b>Grain Silo</b> roofs. Clip or screenshot it: they're random each match and change if you save and quit."],
  ph:[["Cube",MKP("ashes_of_the_damned","necrofluid_gauntlet/cube"),MKQ("ashes_of_the_damned")],["Rooftop symbols",MKP("ashes_of_the_damned","necrofluid_gauntlet/symbols"),MKQ("ashes_of_the_damned")]],q:["a12","a13"]},
 {t:"Set the cube and take the Gauntlet",loc:"Vandorn Farm cellar",b:["Interact with each side of the cube until its three sides show your symbols, then interact with the eye.","The eye disappears. Pick up the Necrofluid Gauntlet."],
  ph:[["Eye on the cube",MKP("ashes_of_the_damned","necrofluid_gauntlet/eye"),MKQ("ashes_of_the_damned")],["Gauntlet pickup",MKP("ashes_of_the_damned","necrofluid_gauntlet/gauntlet_pick_up"),MKQ("ashes_of_the_damned")]]},
 {t:"Survive the lockdown: collect six green orbs",loc:"Vandorn Farm cellar",b:["You're locked in a circle around the cube while green orbs appear around the room.","Shoot an orb with the Gauntlet, then reload to recall the spike and collect it. One spike can pull several at once. Six orbs ends the lockdown."],
  ph:[["Green orb",MKP("ashes_of_the_damned","necrofluid_gauntlet/green_orb"),MKQ("ashes_of_the_damned")]],q:["a14"]}
 ],
 tips:["Pack-a-Punch it before the Yuri's Lab blood ritual — shooting and reloading it heals you a little, and the lockdown blocks normal health regen.","It's also needed for the Teddy Bear relic and the Ol' Tessie toy."]},

speedIntro:"This follows the Google doc's recommended order: start the 3-round lantern timer first, grab the barn bones on the same trip, and do the Cosmodrome code before the Exit 115 lightning.",
steps:[
{id:"a1",t:"Turn on power and build Pack-a-Punch",loc:"Janus Towers → Blackwater → Vandorn Farm → Ashwood",b:["In the starting building, melee the floor for T.E.D.D.'s Head and put it on the car.","At each hub, shoot the growth off the power generator and flip its switch (Vandorn Farm barn, Ashwood upper area, Blackwater Lake).","Park the car inside the Ashwood garage and use the crafting table — Pack-a-Punch mounts on the back of the car."]},
{id:"a2",t:"Get the three diner items",loc:"Exit 115 · Reba's Diner",gate:"Round 5+",b:["<b>Ravager Eyes:</b> on a Ravager round, turn on a Saw Blade trap (2,000) and let Ravagers run into it — they drop the gold item.","<b>Freezer Key:</b> kill zombies inside the diner until the Cook drops it (round 5+).","<b>Abomination Carcass:</b> hold interact on the freezer in the diner's south-west corner (needs the key)."],ph:[["Saw trap",E(1)],["Ravager drop",E(2)],["Cook's key",E(3)],["Freezer",E(4)],["Carcass",E(5)]]},
{id:"a3",t:"Give the car its Abomination Beam",loc:"Ashwood garage",b:["Park in the garage and use the crafting table. Three heads appear on the car's front; fire the beam with R1/RB."]},
{id:"a4",t:"Hoard Husk Chunks",loc:"Fog roads",b:["Blast a purple glowing plant on any fog road with the car beam until one drops the Husk (flesh). You only need one.","Reliable spot: the roadside between Vandorn Farm and Ashwood."],ph:[["Plant",E("6-1")],["Drop",E("6-2")]]},
{id:"a5",t:"Jar of Spores",loc:"Blackwater Lake · cabin kitchen",b:["Turn on Blackwater's power and take the jar from the cabin's ground-floor kitchen shelf."],ph:[["Jar",E(7)]]},
{id:"a6",t:"Fill the jar → Widow's Lantern",loc:"Vandorn Farm · road left of the barn",b:["Place the jar on the red-spored animal carcass on the road just left of the barn. It takes 3 rounds to become the Widow's Lantern — keep working and come back."],ph:[["Carcass",E(8)],["Jar placed",E(9)]]},
{id:"a7",t:"Human Bones",loc:"Vandorn Farm · barn",b:["Hit the left foot (ankle) of the lowest hanging body at the back of the barn with a thrown Combat Axe. The foot drops.","Molotov the foot, wait for the fire to die, pick up the Human Bones.","Free Combat Axe: diner kitchen (some players also find one in the Blackwater cabin). Free Molotov: in front of the Ashwood garage."],ph:[["Hanging foot",E(10)],["Molotov",E(11)],["Pickup",E(12)]]},
{id:"a8",t:"Kill Uber Klaus → Stabilizer Chip",loc:"Janus Towers Plaza · by the Blackwater gate",gate:"Round 8+",b:["Uber Klaus comes out of the Project Janus container / burning truck on the cliff by the west (Blackwater) exit. Bring a Pack-a-Punched weapon. Kill him and grab the card/chip."],ph:[["Spawn spot",E(13)],["Chip",E(14)]]},
{id:"a9",t:"Wake Klaus in his cell",loc:"Ashwood · Sheriff's Office (jail)",b:["Left zipline, back-left house. Insert the chip at the cell terminal.","Throw Stun Grenades (two usually does it) so they burst just in front of Klaus and to his left. He gets a stun icon and bursts through the roof."],ph:[["Cell",E(15)]]},
{id:"a10",t:"Klaus repairs the Cosmodrome machine → Aether Barrel",loc:"Zarya Cosmodrome · lower level",b:["Hold your tactical button (L1/LB) to command Klaus. If he vanishes, call him from a radio (one is right of Wisp Tea).","Open the path downstairs; send Klaus to the control switch right of the glass canister. A red circle appears (or flip the light green → red yourself).","One player stands in the circle to be scanned while others defend. Take the canister (Aether Barrel)."],ph:[["Console",E(16)]]},
{id:"a11",t:"Charge the barrel at three generators",loc:"Ashwood · Blackwater · Vandorn",b:["Slot the barrel into each power generator and defend it while it charges. Each charge is timed — drive it to the next generator before it drains. Any order works; the doc runs Ashwood → Blackwater → Farm."]},
{id:"a12",t:"Wake the Wonder Weapon cube",loc:"Vandorn Farm · bottom of the barn (cellar)",b:["Drop the fully charged barrel at the cube's eye within 1:45. Green icons light up."],ph:[["Cube",E(17)]]},
{id:"a13",t:"Enter the rooftop glyphs → Necrofluid Gauntlet",loc:"Janus ↔ Vandorn jump pad",b:["Take the jump pad between Janus Towers and Vandorn Farm. Mid-air, look at the farm rooftops for three red symbols (random each match). Save a clip.","Set the cube's three sides to match, interact with the eye, take the Gauntlet."],ph:[["Rooftop glyphs",E(18)],["Cube icons",E("18-2")]]},
{id:"a14",t:"Clear the six cysts",loc:"Vandorn Farm · cellar",b:["Shoot each green cyst with primary fire, then recall with alt-fire. Clear all six."],ph:[["Cysts",E(19)]]},
{id:"a15",t:"Kill the Zursa bear with the car beam",loc:"Vandorn Farm · road",gate:"Round 16",b:["A Zursa spawns on the road. Kill it with Ol' Tessie's Abomination Beam for the Mysterious Limb (Bear Limbs)."],ph:[["Bear",E("20-1")],["Limb",E("20-2")]]},
{id:"a16",t:"Break the mirror → Powder",loc:"Ashwood · Tailor Shop",b:["Needs Wisp Tea (Cosmodrome). Kill zombies by the mirror until Wisp Tea procs and the mirror changes, then shoot it with the Gauntlet for the Powder of the Forgotten."],ph:[["Mirror",E(21)],["Powder",E(22)]]},
{id:"a17",t:"Yuri's Lab cipher and blood ritual",loc:"Zarya Cosmodrome · Yuri's Lab",b:["Interact ONLY with the Powder dish (5th from left). Three lines of pigpen-style glyphs appear on the wall.","Decode them (Codes tab) and interact with those three ingredients top line to bottom line. Wrong = retry next round.","Interact with the middle vial to start the blood ritual. No health regen and the donor must not go down. Bring high PaP, good rarity, full perks, tier 3 armor and Monkey Bombs. Interact with the same spot when it ends."],ph:[["Bowls",E("23-1")],["Wall glyphs",E("23-2")],["Glyph key",PX("black-ops-7-zombies-ee-chalkboard-glyph-puzzle-solution")]]},
{id:"a18",t:"Pull the three keys to the Ashwood cube",loc:"Fog roads → Ashwood · Rabbit Alley",b:["Shoot each key with the Gauntlet and alt-fire to explode the barb; pick it up and deliver it to the cube/rock in Rabbit Alley before taking the next. Any order.","Each key spawns in one of 3 spots on its road, and has a drawback while carried."],ph:[["Delivery rock",E(24)]],keys:true},
{id:"a19",t:"Install the DG-2 turret",loc:"Ashwood garage",b:["After the third key, the cube leaves the DG-2 Turret Barrel. Install it at the garage's vehicle upgrade table."],ph:[["Barrel",E(25)]]},
{id:"a20",t:"Lure three revived people into the lightning",loc:"Ashwood clock → Exit 115",gate:"Lightning rounds",b:["Needs Melee Macchiato (Blackwater). Only on rounds when colored lightning hits Exit 115 (wait a few rounds if not).","Shoot the floating clock above the Ashwood garage with the DG-2, then shoot a clock face with the Gauntlet and recall — you're “purple” for 1 minute. At Exit 115, shoot the clock above the diner to freeze the lightning.","<b>Red:</b> beam the back of the red container/trailer, then ram it; a zombie falls out.","<b>Yellow:</b> call Klaus from the Workshop/service-station radio (2,000) and send him to the dead mechanic beside the car.","<b>Blue/Purple:</b> with Melee Macchiato, melee the diner cash register.","Lead each one alive into its color. Completed colors stay done; repeat until all three are in."],ph:[["Clock tower",E(26)],["Clock hand",E(27)],["Roof clock",E("28-1")],["Roof clock 2",E("28-2")],["Register",E(30)],["Trailer",E("29-1")],["Trailer 2",E("29-2")],["Trailer 3",E("29-3")],["Mechanic",E("31-1")],["Mechanic 2",E("31-2")],["Mechanic 3",E("31-3")]]},
{id:"a21",t:"Freeze the satellites and launch the rocket",loc:"Ashwood clock → Cosmodrome Control Room",b:["Go purple, shoot one spinning satellite dish at the Cosmodrome; go purple again and shoot the other. (The upper Ashwood jump pad goes straight there.)","The right-side computers in the Control Room show a 6-letter word. Convert with A=0, B=1… and shoot each screen's red button when it shows that number (Codes tab). Then press the middle button — the rocket launches."],ph:[["Satellite",E("32-1")],["Word screens",E("32-2")],["Cypher key",PX("black-ops-7-ee-computer-screen-cypher-solution")],["Number screens",E("32-3")],["Buttons",E("32-4")]]},
{id:"a22",t:"Dining-room clock",loc:"Ashwood clock → Vandorn farmhouse",b:["Go purple and jump-pad to the farm. Check the wall clock's hour hand (6, 9 or 12) and stand on that numeral on the floor by the table.","When the father's eyes turn red, shoot him with the Gauntlet. A blue electric glow means it worked."],ph:[["Wall clock",E("33-1")],["Floor numerals",E("33-2")],["Father",E("33-3")],["Success",E("33-4")]]},
{id:"a23",t:"Collect the four family artifacts",loc:"Vandorn Farm",b:["<b>Teddy / Tasty-Face:</b> cabinet right of Stamin-Up, upstairs.","<b>Pa's Pigsticker:</b> table in the shed/garage by the Mystery Box.","<b>Ma's Chalice (cup):</b> the bathtub in the cellar where the cube is.","<b>Junior's Fun-Face:</b> back-left corner of the barn upstairs, mask on a stick."],ph:[["Tasty-Face",E("34-1")],["Pigsticker",E("34-2")],["Chalice",E("34-3")],["Fun-Face",E("34-4")]]},
{id:"a24",t:"Defend the ritual",loc:"Vandorn Farm · yard",b:["Place the items in the four red circles outside and defend them. Monkey Bombs and the trap (2,000) help."],ph:[["Circles",E("35-1")]]},
{id:"a25",t:"Projector reels",loc:"Ashwood clock → Blackwater cabin",b:["Interact with the blue soul on the Blackwater dock. Go purple and shoot the projector inside the cabin.","It flashes four slides: front, left (shed), right (boathouse), back — random order. Record it, then shoot the four reels in that order (Codes tab). Wrong order = jumpscare.","Hold interact on the glowing box at the foot of the bed by Speed Cola, then summon Klaus to it. He carries it to the dock."],ph:[["Blue soul",PX("black-ops-7-easter-egg-cabin-soul")],["Projector",PX("black-ops-7-easter-egg-cabin-projector")],["Box",PX("black-ops-7-easter-egg-cabin-crate")],["Klaus at box",PX("black-ops-7-easter-egg-cabin-klaus")]]},
{id:"a26",t:"Start the final encounter",loc:"Blackwater · docks",b:["Park a fully repaired car at Blackwater, bring Monkey Bombs, use pause time now. Talk to Klaus on the dock; everyone confirms."],ph:[["Klaus",PX("black-ops-7-easter-egg-klaus-end")]]},
{id:"a27",t:"Drive over the 12 wisps",loc:"Four fog roads, one lap",b:["Drive through 3 red wisps (white smoke around them) on each road: Blackwater → Janus (Monolith Forest), Janus → Farm (Collapsed Tower), Farm → Ashwood (Grounded Ship), Ashwood → Blackwater (Lost Cabins). Get all 12 within the time limit.","Missing one sounds a gong — talk to Klaus again next round."],ph:[["Red wisp",PX("black-ops-7-easter-egg-final-step")]]},
{id:"a28",t:"Boss: Veytharion",loc:"Boss arena",b:["One player always drives; runners revive and repair (150 salvage). Bring GobbleGums for armor and revives.","Ram the orange mouths (use the center stairs as a ramp) while runners shoot.","When he goes immune, drive through the purple/blue energy on the ground, then ram him.","Around half health he charges a one-shot beam: the driver rams the charging eye, everyone else hides behind a pillar.","<b>Afterwards don't exfil yet:</b> walk to the docks and interact with the relic to unlock Cursed relics for this map."]}
],
speed:["a1","a5","a6","a7","a2","a3","a4","a8","a9","a10","a11","a12","a13","a14","a16","a15","a17","a18","a19","a21","a20","a22","a23","a24","a25","a26","a27","a28"],
speedNotes:{a1:"Doc tip: visit Klaus' jail room once while you're in Ashwood so the later step is quick. Grab the free Molotov in front of the garage.",a5:"Turn on Blackwater first and take the jar; buy Melee Macchiato there too (needed later).",a6:"Starts a 3-round timer — do it before anything else.",a7:"Same trip as the carcass. Combat Axe: diner kitchen or Blackwater cabin.",a2:"The doc notes the Ravager Eyes can be pushed later if a Ravager round isn't coming.",a8:"Have a Pack-a-Punched weapon ready for him.",a16:"Do the mirror while waiting for round 16. Buy Wisp Tea at Cosmodrome during the barrel step.",a21:"Doc order: the Cosmodrome code before the Exit 115 lightning, since lightning can take a few rounds to show up."},

side:[
{t:"Soda Sommelier — Quick Revive",r:"Free Quick Revive",req:"Once per match; touch only the three right items",b:["Toilet Cleaner — Janus Towers server room desk.","Fish — Blackwater dock behind the cabin.","Stim Shot — Cosmodrome Control Room shelf by the door.","Mix at the glowing cup on the Exit 115 diner soda fountain."],ph:[["Fountain",MIX("mixologist-machine-1")],["Cleaner",MIX("1-1")],["Fish",MIX("1-3")],["Stim Shot",MIX("1-5")]]},
{t:"Soda Sommelier — Juggernog",r:"Free Juggernog",req:"Once per match",b:["Plant (leaf) — Janus Towers, on the climbable broken road ahead-right of spawn.","Jar of Milk — Vandorn barn, through the crack at the top of the cellar stairs.","Carton of Eggs — diner kitchen, metal shelf behind the counter."],ph:[["Leaf",MIX("4-1")],["Milk",MIX("4-3")],["Eggs",MIX("4-5")]]},
{t:"Soda Sommelier — Speed Cola",r:"Free Speed Cola",req:"Once per match",b:["Berries (leaf) — Blackwater exit toward spawn, behind the broken car (go prone).","Dried Peppers — Ashwood Hargrove's Mercantile, small crate on the shelf left of the door by the armor wall-buy.","Sugar Packets — diner counter right of the fountain (green box)."],ph:[["Berries",MIX("3-1")],["Peppers",MIX("3-3")],["Sugar",MIX("3-5")]]},
{t:"Soda Sommelier — Stamin-Up",r:"Free Stamin-Up",req:"Once per match",b:["Plant (wooden crate) — Vandorn cellar, first shelf on the right.","Bag of Beans (red/white sack) — Hargrove's Mercantile, bottom of the shelf behind the table.","Gas Canister — Exit 115, behind the service station by the buyable door."],ph:[["Crate",MIX("2-1")],["Beans",MIX("2-3")],["Gas can",MIX("2-5")]]},
{t:"Ghost Twins",r:"Loot, including a free Wisp Tea",b:["Interact with the TV in the Vandorn farmhouse.","Find the twins under the barn playing tic-tac-toe, then return to the TV.","Find both twins in the generator area for the loot."]},
{t:"Ray Gun Mark II",r:"Free Ray Gun Mark II + 1,500 essence",req:"After round 18",b:["Ride the jump pads in this order: Janus Towers → Blackwater Lake → Ashwood → Exit 115 → Cosmodrome → Ashwood → Farm → Janus Towers.","Survive four rounds at Janus Towers, read the blinking code, follow the pad sequence it shows, then hit the purple portal in the sky."]},
{t:"Toxic Spores",r:"Loot; Toxic Growth plants can drop a Raw Aetherium Crystal (free PaP)",b:["Get a Fumigator: Vandorn barn upstairs, the spawn area, Ashwood by the VS Recon wall-buy, or the Blackwater shed.","Fumigate toxic plants and protect them until they bloom. The Toxic Growth field upgrade (level 29) gives better rewards, including a chance at a crystal that Pack-a-Punches the gun in your hands."]},
{t:"Lucidity",r:"Tank Dempsey turns into a Disciple",req:"Play as Tank Dempsey",b:["Interact with the dog tags in the Crashed Rocket area.","Follow the floating black orb to finish."]},
{t:"Cursed Bear",r:"Not documented by the sources",req:"Death Perception",b:["In Orda Graveyard, walk slowly over five bear footprints.","Kill the bear in the forest area to finish."]},
{t:"Free power-ups",r:"Max Ammo, Insta-Kill, Max Armor, Nuke, Double Points, Full Power, Bonus Points, then Fire Sale, then a free perk",b:["Shoot the nine hidden power-up icons. Fire Sale appears after the first seven; the perk appears after the other eight. Exact spots aren't listed in the sources used here."]},
{t:"Song: “Turn to Ashes”",r:"Music (Elena Siegman)",b:["Janus Towers server room.","Ashwood, ledge by the VS Recon wall-buy.","Exit 115, truck passenger seat."]}
],

relicNote:"Beat the main quest and touch the relic on the Blackwater dock first. Relics only drop in Cursed mode. Grim trials open at round 20; Sinister at 40 (needs a Tier I Cursed run); Wicked at 60 (needs Tier II).",
relics:[
{n:"Lawyer's Pen",tier:"grim",e:"Shock Mimic props spawn around the map.",trial:"All zombies are Mimics.",u:["Round 20+. Napalm Burst ammo mod (or Molotovs).","Light 3 candles: Vandorn farmhouse upstairs nightstand; Lost Cabins destroyed house by the cabinet; Ashwood Ruby Rabbit, end of the shelf right of Juggernog (dark — spray it).","Green portal on the back of the Vandorn barn."],ph:[["Candle 1",RL("1-candle-1")],["Candle 2",RL("1-candle-2-1")],["Candle 3",RL("1-candle-3")],["Portal",RL("1-trial-1")]]},
{n:"Dragon Wings",tier:"grim",e:"No power-ups spawn.",trial:"Power-ups damage you.",u:["Round 20+. On the Farm → Janus jump pad, shoot 3 purple targets mid-air: left on a pylon, right on the broken bridge, straight ahead on the tower wall.","Portal on the side of the farmhouse."],ph:[["Target 1",RL("2-1")],["Target 2",RL("2-2")],["Target 3",RL("2-3")],["Portal",RL("2-4")]]},
{n:"Teddy Bear",tier:"grim",e:"Zombies spawn 75% faster (shorter round delay).",trial:"Each shot costs 100 essence.",u:["Needs the Gauntlet and Aether Shroud (Group Shroud + Extra Charge help). The teddies only show during Aether Shroud; the 10th appears after round 20.","Shoot and pull in all 10 Mister Peeks dolls (photos show the aim points).","Portal by the Vandorn shed (Mystery Box / armor wall-buy). Bring Kill Joy and turret grenades."],ph:[["1 silo",RL("3-1")],["2 ship",RL("3-2")],["3 gate",RL("3-3")],["4 toilet",RL("3-4")],["5 hut roof",RL("3-5")],["6 church",RL("3-6")],["7 Rabbit Alley",RL("3-7")],["8 pole",RL("3-8")],["9 console",RL("3-9")],["10 road sign",RL("3-10")]]},
{n:"Vril Sphere",tier:"sin",e:"Four-perk limit.",trial:"Purchases disabled.",u:["Round 40+. Launch a Doppelghast with a jump pad and kill it.","Portal at Zarya Cosmodrome. Buy everything before entering."]},
{n:"Samantha's Drawing",tier:"sin",e:"Your weapons swap every round (rarity and PaP kept).",trial:"No ammo.",u:["Through round 39, feed Chompy (the garbage can) guns in rarity order: grey, green, blue, purple, gold.","On round 40, feed it a Ray Gun. Portal at Zarya Cosmodrome."]},
{n:"Focusing Stone",tier:"sin",e:"No self-revives.",trial:"No essence.",u:["Round 40+. Get the wine bottles: one from meleeing a Zursa and one from a T.E.D.D. trial completed at Legendary.","Recreate the order they exploded in at the Blackwater cabin table. Portal at Zarya Cosmodrome."]},
{n:"Blood Vial",tier:"wic",e:"No augments.",trial:"All weapon damage halved.",u:["Find and answer the ringing red phone (other guides say five times, once per 10-round window from round 10 to 60). Portal at the Blackwater cabin."]},
{n:"TranZit Bus",tier:"wic",e:"Enemies heal.",trial:"Zombies are only damaged by other zombies (use Brain Rot).",u:["Round 60+. Clear a full round killing only with Ol' Tessie."]},
{n:"Dragon",tier:"wic",e:"No ammo crates.",trial:"Zombies only take explosive damage.",u:["Round 60+ in a Tier II run: beat Veytharion and keep playing instead of exfilling. Red portal outside the Blackwater house."]}
],

intel:[
{k:"Audio log",n:"Tilling the Earth",a:"Vandorn Farm",loc:"Farmhouse kitchen, on the pan"},
{k:"Audio log",n:"Meat the Vandorns",a:"Vandorn Farm",loc:"Basement shelf"},
{k:"Audio log",n:"Ground Control",a:"Zarya Cosmodrome",loc:"Control Room"},
{k:"Audio log",n:"What Came After",a:"Zarya Cosmodrome",loc:"Flame trench"},
{k:"Audio log",n:"She Got Hers",a:"Exit 115",loc:"Diner kitchen"},
{k:"Audio log",n:"He Got His",a:"Exit 115",loc:"Self-serve station"},
{k:"Audio log",n:"The Price You Pay",a:"Ashwood",loc:"Tailor Shop",ch:"Tailor-Made"},
{k:"Audio log",n:"Craftsmanship",a:"Ashwood",loc:"Ruby Rabbit desk",ch:"Top Shelf Spirits"},
{k:"Audio log",n:"Cold Blooded Thriller",a:"Blackwater Lake",loc:"Cabin dock house",ch:"Life Preserver"},
{k:"Audio log",n:"The Fate of the Flock",a:"Ashwood",loc:"Garage",ch:"Smithy"},
{k:"Audio log",n:"Scene 27: The Drowning",a:"Blackwater Lake",loc:"Cabin, near a film reel spot"},
{k:"Audio log",n:"Study Room Monologue Rehearsal",a:"Blackwater Lake",loc:"Cabin, near a film reel spot"},
{k:"Audio log",n:"Confrontation in the Parlor — Camera B",a:"Blackwater Lake",loc:"Cabin, near a film reel spot"},
{k:"Audio log",n:"Director's Notes: Improv Test",a:"Blackwater Lake",loc:"Cabin, near a film reel spot"},
{k:"Document",n:"Cut",a:"Blackwater Lake",loc:"Hunting shack dartboard",ch:"Crickets"},
{k:"Document",n:"Maintenance",a:"Zarya Cosmodrome",loc:"Control Room papers",ch:"Rocket, Paper, Scissors"},
{k:"Document",n:"Signal Fires",a:"Ashwood",loc:"Ascender platform, right side",ch:"Ascend, Descend"},
{k:"Document",n:"Playmates",a:"Vandorn Farm",loc:"Haystacks",ch:"Like a Needle..."},
{k:"Document",n:"Evidence",a:"Exit 115",loc:"Auto shop spray cans",ch:"Oil Change"},
{k:"Document",n:"Good Game",a:"Janus Towers Plaza",loc:"Melee the tank with Melee Macchiato",ch:"Tanks a Lot"},
{k:"Artifact",n:"T.E.D.D. Head",a:"Janus Towers Plaza",loc:"Main quest (power)"},
{k:"Artifact",n:"Mirror of the Forgotten",a:"Ashwood",loc:"Main quest (mirror step)"},
{k:"Artifact",n:"DG-2 Turret",a:"Ashwood",loc:"Main quest (keys)"},
{k:"Artifact",n:"Seal of Sorrow",a:"Blackwater Lake",loc:"Main quest progression"},
{k:"Artifact",n:"Helion Horn",a:"Zarya Cosmodrome",loc:"Main quest progression"},
{k:"Artifact",n:"Necrofluid Gauntlet",a:"Vandorn Farm",loc:"Build the Wonder Weapon"}
],

areas:["Janus Towers Plaza","Monolith Forest","Blackwater Lake","Lost Cabins","Collapsed Tower","Vandorn Farm","Grounded Ship","Ashwood","Orda Graveyard","Exit 115","Crashed Rocket","Zarya Cosmodrome"],
pins:[
{a:"Janus Towers Plaza",c:"quest",n:"T.E.D.D.'s Head",d:"Melee the floor in the starting building."},
{a:"Janus Towers Plaza",c:"quest",n:"Uber Klaus (R8+)",d:"Spawns by the Project Janus container / burning truck near the Blackwater gate."},
{a:"Janus Towers Plaza",c:"egg",n:"Ray Gun Mk II start",d:"After round 18: jump-pad route and the purple sky portal."},
{a:"Janus Towers Plaza",c:"music",n:"Headset 1",d:"Server room."},
{a:"Janus Towers Plaza",c:"tool",n:"Fumigator",d:"Spawn area."},
{a:"Janus Towers Plaza",c:"relic",n:"Teddy 3",d:"On top of the arch to Blackwater (Aether Shroud)."},
{a:"Blackwater Lake",c:"quest",n:"Jar of Spores",d:"Cabin kitchen shelf."},
{a:"Blackwater Lake",c:"quest",n:"Projector + 4 reels",d:"Cabin projector room; reels in the shed, boathouse, upstairs and behind the cabin."},
{a:"Blackwater Lake",c:"quest",n:"Final encounter start",d:"Talk to Klaus on the dock."},
{a:"Blackwater Lake",c:"tool",n:"Fumigator",d:"Blackwater shed."},
{a:"Blackwater Lake",c:"perk",n:"Melee Macchiato",d:"Perk machine in the cabin — needed for the register."},
{a:"Blackwater Lake",c:"relic",n:"Teddy 4",d:"Upstairs bathroom toilet, through the window left of Speed Cola."},
{a:"Blackwater Lake",c:"relic",n:"Focusing Stone bottles",d:"Cabin table."},
{a:"Monolith Forest",c:"quest",n:"3 final wisps",d:"Blackwater → Janus road."},
{a:"Collapsed Tower",c:"quest",n:"3 final wisps",d:"Janus → Farm road."},
{a:"Lost Cabins",c:"quest",n:"3 final wisps",d:"Ashwood → Blackwater road."},
{a:"Lost Cabins",c:"relic",n:"Candle 2 / Teddy 5",d:"Candle in the destroyed house; teddy on the small hut roof."},
{a:"Vandorn Farm",c:"quest",n:"Lantern carcass",d:"Road left of the barn (3 rounds)."},
{a:"Vandorn Farm",c:"quest",n:"Human Bones",d:"Barn: axe the hanging foot, Molotov it."},
{a:"Vandorn Farm",c:"ww",n:"Wonder Weapon cube",d:"Cellar under the barn; glyphs on the rooftops."},
{a:"Vandorn Farm",c:"quest",n:"Zursa (R16)",d:"Road; kill with the car beam."},
{a:"Vandorn Farm",c:"quest",n:"Dining-room clock + artifacts",d:"Farmhouse table; four artifacts around the farm."},
{a:"Vandorn Farm",c:"egg",n:"Ghost Twins TV",d:"Farmhouse TV → twins under the barn."},
{a:"Vandorn Farm",c:"tool",n:"Fumigator",d:"Barn upstairs."},
{a:"Vandorn Farm",c:"relic",n:"Relic portals",d:"Grim portals at the barn, farmhouse and shed; Candle 1 upstairs; Teddy 1 on the silo."},
{a:"Grounded Ship",c:"quest",n:"Green key + 3 wisps",d:"Key: container, cabin window or under the ship."},
{a:"Grounded Ship",c:"relic",n:"Teddy 2",d:"Inside the ship, on a barrel over the staircase."},
{a:"Ashwood",c:"quest",n:"Garage (PaP, upgrades)",d:"Vehicle upgrade table; free Molotov out front."},
{a:"Ashwood",c:"quest",n:"Klaus' cell",d:"Sheriff's Office."},
{a:"Ashwood",c:"quest",n:"Mirror",d:"Tailor Shop."},
{a:"Ashwood",c:"quest",n:"Key cube",d:"Rabbit Alley."},
{a:"Ashwood",c:"quest",n:"Floating clock",d:"Above the garage; shoot with DG-2."},
{a:"Ashwood",c:"music",n:"Headset 2",d:"Ledge by the VS Recon wall-buy."},
{a:"Ashwood",c:"tool",n:"Fumigator",d:"Near the VS Recon wall-buy."},
{a:"Ashwood",c:"relic",n:"Candle 3 / Teddies 6–7",d:"Ruby Rabbit shelf; dark church; Rabbit Alley stairs."},
{a:"Orda Graveyard",c:"quest",n:"Red key",d:"Behind the Project Janus vehicle, or in a dinosaur skull."},
{a:"Orda Graveyard",c:"egg",n:"Cursed Bear footprints",d:"Death Perception; walk slowly over five prints."},
{a:"Exit 115",c:"quest",n:"Diner items",d:"Ravager Eyes, Freezer Key, carcass."},
{a:"Exit 115",c:"quest",n:"Lightning revives",d:"Register, red trailer, mechanic."},
{a:"Exit 115",c:"perk",n:"Soda fountain",d:"Mix one free perk per match."},
{a:"Exit 115",c:"music",n:"Headset 3",d:"Truck passenger seat."},
{a:"Exit 115",c:"tool",n:"Combat Axe",d:"Diner kitchen."},
{a:"Exit 115",c:"relic",n:"Teddy 10",d:"Road sign above the highway, from the diner roof."},
{a:"Crashed Rocket",c:"quest",n:"Yellow key",d:"Cliff top, red pylon or radar building."},
{a:"Crashed Rocket",c:"egg",n:"Lucidity (Dempsey)",d:"Dog tags."},
{a:"Zarya Cosmodrome",c:"quest",n:"Aether Barrel",d:"Lower level console with Klaus."},
{a:"Zarya Cosmodrome",c:"quest",n:"Yuri's Lab",d:"Cipher and blood ritual."},
{a:"Zarya Cosmodrome",c:"quest",n:"Satellites + Control Room code",d:"Rocket launch."},
{a:"Zarya Cosmodrome",c:"perk",n:"Wisp Tea",d:"Needed for the mirror."},
{a:"Zarya Cosmodrome",c:"relic",n:"Sinister portals / Teddies 8–9",d:"Sinister trials start here."}
],

toy:{name:"Ol' Tessie",prep:"Grab a Fumigator early, build the Gauntlet and have Dark Flare charged. Aether Shroud or Monkey Bombs help in the fog.",
 steps:[["Find the Twins","They start in Ashwood, on the fog road between Blackwater and Ashwood, at the Lost Cabins, or on the boat between the Farm and Ashwood. Walk up to them; they reappear on the Vandorn barn, looking at a toy box over the windmill.",[["Twins",SK("6ab29126451db5.43388963")]]],
  ["Bring the box down","Drag the floating box down with the Gauntlet, then clear its storm with Dark Flare until it opens.",[["Toy box",SK("6ab29143982094.61992810")]]],
  ["Three pink crystals","In the Monolith Forest fog, knock three pink crystals off the monoliths with the Gauntlet and interact with each using your Fumigator.",[["Crystals",SK("6ab291561f9239.85828561")]]],
  ["Meteor","A 115 meteor lands at the Blackwater entrance. Fumigate it, flip the round, take the 115 rock.",[["Meteor",SK("6ab29168401d68.71735042")]]],
  ["Claim and exfil","Put the rock in the toy box for loot and the Ol' Tessie toy. Exfil successfully.",[["Exfil",SK("6ab29179085137.60226406")]]]]},
codes:"ashes",
src:[["MargwaNetwork — Ashes","https://margwa.net/ashes-of-the-damned"],["BO7 Easter Eggs (Google Doc)","https://docs.google.com/document/u/0/d/1zFsG8A0BA_jUt8BNoAd2lmw36OR35ecOzicHwoXsexw/mobilebasic"],["PowerPyx — main quest","https://www.powerpyx.com/cod-black-ops-7-ashes-of-the-damned-easter-egg-guide/"],["PowerPyx — free perks","https://www.powerpyx.com/cod-black-ops-7-zombies-how-to-get-all-free-perks-mixologist/"],["PowerPyx — Grim relics","https://www.powerpyx.com/cod-black-ops-7-expert-curator-trophy-3-easiest-relics/"],["Skycoach — Super EE","https://skycoach.gg/blog/call-of-duty/articles/super-easter-egg-guide"]]
});
