MAPS.push({
id:"astra", slug:"astra-malorum", name:"Astra Malorum", color:"#26a69a", season:"Season 1", date:"Dec 4, 2025",
blurb:"An observatory on a rock inside Saturn's rings, with a killer robot (O.S.C.A.R.) roaming the halls and a teleporter to Mars.",
ww:"LGM-1", boss:"Caltheris", reward:"“Bottled Up” Nikolai skin + calling card",
mapImg: MGMAP("astra-malorum"),

wwInfo:{what:"The LGM-1 drops after you kill O.S.C.A.R. with all three of the map's traps (any order). You need it to wake the Resonance Pillars on Mars.",
 steps:[
 {t:"Pack-a-Punch → O.S.C.A.R. starts roaming",loc:"Observatory Dome",b:["Turning on Pack-a-Punch spawns O.S.C.A.R., a high-health elite who roams the map and attacks anyone he sees.","Don't kill him with guns. He has to die once to each of the three traps below, in any order. The third trap kill drops the LGM-1."],
  ph:[["O.S.C.A.R.",MKP("astra_malorum","lgm1/oscar"),MKQ("astra_malorum")]],q:["m1"]},
 {t:"Collect the Electro-Volt parts",b:["<b>Damaged Drone:</b> shoot one of the drones circling O.S.C.A.R.; the first one you destroy falls to the floor. Pick it up.","<b>Car Battery:</b> with a Pack-a-Punched gun, shoot the hood of the wrecked Ol' Tessie at the Crash Site <b>from close range</b>. The battery flies out. This also teleports O.S.C.A.R. to the Crash Site and spawns purple-eyed zombies, so be ready.","<b>Aberrant Wiring:</b> one lamppost on the map is blinking (only one per game). Shoot its light until the wiring drops. Stargazer's Courtyard is the usual place to look first."],
  spots:[{h:"The three parts",list:[["Damaged Drone",MKP("astra_malorum","lgm1/damaged_drone"),MKQ("astra_malorum")],["Car Battery (out of Ol' Tessie's hood)",MKP("astra_malorum","lgm1/car_battery"),MKQ("astra_malorum")],["Aberrant Wiring (blinking lamppost)",MKP("astra_malorum","lgm1/aberrant_wiring"),MKQ("astra_malorum")]]}],
  ph:[["Drone to shoot",MKP("astra_malorum","lgm1/drone"),MKQ("astra_malorum")],["Ol' Tessie's hood",MKP("astra_malorum","lgm1/tessie_hood"),MKQ("astra_malorum")],["Blinking lamppost",
   "https://image.thenerdstash.com/2025/12/Aberrant-Wires-Astra-Malorum-1024x576.jpg","https://thenerdstash.com/how-to-get-lgm-1-wonder-weapon-in-astra-malorum-black-ops-7-zombies/"]],q:["m3"]},
 {t:"Trap 1 · Electro-Volt Projector",loc:"The Luminarium (behind Juggernog)",b:["Insert the drone, battery and wiring at the projector. A non-lethal version of the trap is now free to turn on.","Bring O.S.C.A.R. into the room, switch it on and keep him inside until he dies. Don't leave the room."],
  ph:[["Projector",MKP("astra_malorum","lgm1/electro_volt_trap"),MKQ("astra_malorum")],["Room overview","https://image.thenerdstash.com/2025/12/Luminarium-Trap-Astra-Malorum-1024x576.jpg","https://thenerdstash.com/how-to-get-lgm-1-wonder-weapon-in-astra-malorum-black-ops-7-zombies/"]]},
 {t:"Trap 2 · Model Rocket Thrusters",loc:"Museum Infinitum (in front of Speed Cola)",b:["Equip Cryo-Freeze (the Twins side egg gives it free if it's still locked). Shoot three purple Aether crystals around the map; each drops an Absolute Zero Fragment.","Lead O.S.C.A.R. to the model rocket, then interact with the wooden panel beside it. A countdown starts and the rocket puffs white smoke.","He has to be standing in that smoke, <b>behind the rocket's exhaust</b>, when it hits 0. If he survives, you need three new fragments (the crystals respawn every few rounds)."],
  spots:[{h:"What to look for",list:[["Purple Aether crystal (shoot with Cryo-Freeze)",MKP("astra_malorum","lgm1/aether_crystals"),MKQ("astra_malorum")],["Absolute Zero Fragment drop",MKP("astra_malorum","lgm1/absolute_zero_fragment"),MKQ("astra_malorum")]]}],
  ph:[["Model rocket",MKP("astra_malorum","lgm1/model_rocket"),MKQ("astra_malorum")],["Wooden panel",MKP("astra_malorum","lgm1/model_rocket_panel"),MKQ("astra_malorum")]]},
 {t:"Trap 3 · Telescope Beam",loc:"Observatory Dome",b:["Nine valves ring the dome and one is steaming. Shoot it, then shoot the next one that starts steaming: five in a row, quickly. Too slow and you wait for the next round.","When the telescope stops moving, use the <b>left side of the organ</b> to open the sky view and park the cursor just beside the Sun, not on it.","Bring O.S.C.A.R. under the telescope (just in front of Pack-a-Punch). Use the organ again and move onto the Sun; you get kicked out of the view when it's right. Keep him in the beam until he dies."],
  spots:[{h:"Valve cheat sheet · two are above and two below the telescope",list:[["All nine valve positions",MKP("astra_malorum","lgm1/valve_locations"),MKQ("astra_malorum")],["Steaming valve",MKP("astra_malorum","lgm1/steam_valves"),MKQ("astra_malorum")]]}],
  ph:[["Valve close-up",MKP("astra_malorum","lgm1/valve"),MKQ("astra_malorum")],["Telescope",MKP("astra_malorum","lgm1/telescope"),MKQ("astra_malorum")],["Organ (left side)",MKP("astra_malorum","organ_left_side"),MKQ("astra_malorum")],["Where O.S.C.A.R. stands",MKP("astra_malorum","lgm1/where_to_be_under_telescope"),MKQ("astra_malorum")]]},
 {t:"Pick up the LGM-1",b:["The third trap kill drops the LGM-1 for one player to pick up."],
  ph:[["LGM-1 drop",MKP("astra_malorum","lgm1/lgm_1_pickup"),MKQ("astra_malorum")]],q:["m5"]}
 ],
 tips:["Buy Cryo-Freeze early so the three crystals are ready when O.S.C.A.R. respawns.","While you have the telescope open, zoom to Mars and note the coordinates — you need them later."]},

speedIntro:"Follows the Google doc's order: grab the hacksaw and the three planet pages early, and read the Mars coordinates while the telescope is open for the Sunbeam trap.",
steps:[
{id:"m1",t:"Power on and Pack-a-Punch",loc:"Observatory Dome",b:["Find the two parts beside corpses in Machina Astralis (by the main stairs) and the Luminarium, insert them into the organ (Harmonic Oculus) and defend it. Pack-a-Punch drops in."],ph:[["Oculus",SK("6932c5d9e6d515.78171691")],["Defense",SK("6932c5eee64db8.61992242")]]},
{id:"m2",t:"Hacksaw",loc:"Museum Infinitum",b:["Take the right-side door toward Speed Cola, go left, break the display case and pick up the Hacksaw. Needed for the brain."]},
{id:"m3",t:"Electro-Volt parts",loc:"Around the map",b:["<b>Car Battery:</b> shoot the front of the wrecked Ol' Tessie at the Crash Site with a PaP'd gun.","<b>Wires:</b> shoot the one blinking lamppost.","<b>Damaged Drone:</b> shoot one of O.S.C.A.R.'s drones and pick it up."],ph:[["Battery",SK("6932cb9f3fa3d7.30234141")],["Lamppost",SK("6932cb9049e396.66572153")],["Drone",SK("6932c60224ac18.80407754")]]},
{id:"m4",t:"Three planet pages",loc:"Machina Astralis · Luminarium · Archive of Orbis",b:["Each torn page shows a planet and a compass direction (directions change every match): Machina Astralis 2nd-floor desk (Saturn), the desk in the Electro-Volt trap room by Juggernog (Neptune), the middle desk in the Stamin-Up room / Archive (Mars). Write them down."],ph:[["Pages",SK("6932abc5145f34.85438779")]]},
{id:"m5",t:"Kill O.S.C.A.R. with all three traps → LGM-1",loc:"Luminarium · Museum · Dome",b:["Electro-Volt Projector, Rocket trap and Sunbeam — any order (details on the Wonder Weapon tab). The third kill drops the LGM-1."],ph:[["Sunbeam",SK("6932a9136c0989.81920433")],["Projector",SK("6932a9371a5e04.55772617")],["Rocket",SK("6932a96feb7574.88577589")],["LGM-1",SK("6932c61939a599.38903036")]]},
{id:"m6",t:"Planet code → Cryo Key",loc:"Follow O.S.C.A.R. → PaP room",b:["Sneak behind O.S.C.A.R. until he plays “Elimination Twenty: Dr. Thurston” and three planets are named.","Turn them into digits by distance from the sun (Codes tab converter) and enter them at the code machine in the PaP room. Grab the Cryo Key by the body on the lowered platform."]},
{id:"m7",t:"The brain lockdown",loc:"Machina Astralis → Luminarium → teleporter room",b:["Open the cryo capsule (bar area) with the key; cut the brain out with the Hacksaw.","Put it in the container in front of Juggernog and survive the lockdown.","Take the brain to the teleporter-room table (by the library) and hold interact."],ph:[["Brain",SK("6932aa475c0027.74417476")]]},
{id:"m8",t:"Mars coordinates → locker",loc:"PaP telescope → teleporter room upper floor",b:["In the PaP telescope, hover over Mars and note the 4-digit coordinates bottom-left. Enter them on the locker/keypad on the teleporter room's upper floor."],ph:[["Mars",SK("6932d3eab1f459.89515012")]]},
{id:"m9",t:"Library busts → Neptune",loc:"Archive of Orbis (Stamin-Up room)",gate:"First 15–30 s of a round",b:["The brain machine cycles a list of book titles — note them.","Each of the three busts has its own shelves. Turn each bust once per listed book on its shelves (Codes tab tool does the count).","Busts only turn early in a round; you'll hear when they're ready. A ladder hatch opens: climb it and take Neptune."],ph:[["Reading list",SK("6932ab1802d777.81447716")]]},
{id:"m10",t:"Align the planetarium → Mars portal",loc:"Machina Astralis",b:["Place Neptune in the planetarium and interact with the hanging wire at the top of the stairs.","Shoot each planet until it points at its page's compass direction on the sun chandelier.","Interact with the brain; during the lockdown shoot the drones before they reach the portal."],ph:[["Orrery",SK("6932ab6dace254.74575036")]]},
{id:"m11",t:"Mars: pylons → Ascendant Eye",loc:"Mars",b:["Pick up the brain in the middle and place it on the top machine by the portal; hold interact until you hear a bird.","Shoot the four metal orbs outside the map: back-right, back-left, front-right, front-left (no glow = new round, interact with the brain again). Then keep shooting the orb above the portal to hold the bird in place.","Jump through the swooping bird to grab the artifact (Ascendant Eye / scarab) and place it in the back-right statue."],ph:[["Arena",SK("6932abfb95dd76.75773806")],["Pylons",SK("6932ac6abd3738.58950106")],["Eye",SK("6932ac9a0a2152.87702007")]]},
{id:"m12",t:"Organ symbols",loc:"Observatory Dome",b:["Interact with the organ. Four symbols flash on the round screen to the right with a melody; one slot may be static. The static slot is where the fifth Mars symbol goes."],ph:[["Symbols 1",SK("6932acc67b8b78.65929837")],["Symbols 2",SK("6932accc6543a8.56178628")],["Symbols 3",SK("6932acd23b1d36.10957861")],["Symbols 4",SK("6932acd87fbb13.66130285")]]},
{id:"m13",t:"Resonance pillars",loc:"Mars",b:["Shoot the tops of all five pillars with the LGM-1 (any order).","Interact with the pillar bottoms in your symbol order, quickly. Blue = right, red = wrong; three misses and you wait for the next round. Then interact with the brain to start the boss."]},
{id:"m14",t:"Boss: Caltheris",loc:"Mars",b:["Phase 1: fill the soul generators on either side, then hold interact on the brain to fire lasers. Three times.","Phases 2–3: shoot off armor with the LGM-1, then hit the crits. Wall-jump and use low gravity to dodge rocks; jump the ground slam.","Phase 4: the brain gives Max Ammo, Field Upgrade and a big damage boost for ~60 s. Avoid the purple electric pools."],ph:[["Caltheris",SK("6932b5fb76d188.89711955").replace(".png",".jpg")]]}
],
speed:["m1","m2","m4","m3","m5","m8","m6","m7","m9","m10","m11","m12","m13","m14"],
speedNotes:{m2:"Grab the Hacksaw on your first pass through the Museum.",m4:"Write the pages down early — they're static once the match starts.",m5:"While the telescope is open for the Sunbeam, zoom to Mars and copy the coordinates.",m8:"You already have the coordinates from the Sunbeam step — enter them as soon as the locker is available."},

side:[
{t:"Free perk — Museum gramophone",r:"Mystery Perk + salvage",b:["Record: on a wooden pillar top above a zombie window in Museum Infinitum (Speed Cola room) — wall-run to it.","Play it on the Museum gramophone and get 5 melee kills during the song."]},
{t:"Free perk — Luminarium gramophone",r:"Mystery Perk + essence",b:["Record: on top of a bookshelf by the grandfather clock in the Luminarium.","Play it and get 15 kills with a Field Upgrade during the song (Dark Flare works)."]},
{t:"Free perk — Archive gramophone",r:"Mystery Perk + equipment",b:["Record: wooden box on Machina Astralis' middle floor.","Play it on the Archive of Orbis gramophone (by Stamin-Up) and get 5 equipment kills."]},
{t:"Five Skulls",r:"Random perk power-up",req:"A Pack-a-Punched weapon",b:["Shoot each skull to light its eyes, then pick it up: courtyard between the Crash Site and Luminarium; a Museum Infinitum display; a zombie spawn hole by the Stargazer's Courtyard ammo cache; a Machina Astralis display case (left when coming from Stargazer's Courtyard); behind the brick wall in The Veilwalk.","Place all five on the large-mirror cabinet in Machina Astralis and shoot them in the order they light (Simon Says)."]},
{t:"The Twins",r:"Free Cryo-Freeze ammo mod, then loot each time they return",b:["During a special round, interact with the left-most cabinet under the castle painting in Museum Infinitum.","Over the next four rounds one display per round makes noise — find it and interact (Crash Site behind Ol' Tessie, Luminarium, Abyssal Rim by Wisp Tea, Dome corner by the X9 Maverick wall-buy, Veilwalk by the Dome door, Machina Astralis, Museum by the Scholar's Way door)."]},
{t:"Wisp Orbs",r:"Free Ray Gun + secret song “Once In A Blown Up Moon”",b:["Nine lanterns: two at the Crash Site, three in the courtyard in front of the Luminarium, two at the back of the Luminarium, two in Scholar's Way.","Aim at the lit lantern to take its wisp, melee to throw it into an unlit one; repeat until all nine are lit. Flip the round — wisps turn gold (carry up to 5; each kills ~5 zombies).","From round 16 a rocket floats in front of Saturn. Hit it with a gold wisp: it drops a Ray Gun. Aim at it long enough and the song plays."]},
{t:"DG-2 space trip",r:"DG-2 turret for Ol' Tessie + song “Pareidolia”",b:["By Wisp Tea (Abyssal Rim), throw a grenade at the nearby asteroid to pull it closer, then sprint and wall-jump off its left side.","You float through space back to the Crash Site; grab the DG-2 on the way and mount it on Ol' Tessie (great against O.S.C.A.R.)."]},
{t:"Time Dilation",r:"Zombies slowed for 60 seconds (once per round)",b:["Quickly melee five grandfather clocks: Luminarium by the bookshelves, Museum near Speed Cola, two in Machina Astralis (bottom and middle floors), Archive by Stamin-Up."]},
{t:"Bongo the friendly Ravager",r:"A Ravager plays cymbals for you for a few rounds",b:["Killing O.S.C.A.R. drops the Shiny Trinket (replaces your tactical). Find the green-eyed Ravager outside the playable area (white minimap dot) and throw the trinket at it. Three times."]},
{t:"Echoes of the Damned (Nikolai)",r:"Molotov, Legendary Echo 12, Dark Ops calling card",req:"Play as Nikolai",b:["Lower Abyssal Rim: throw a Molotov by the ammo cache to reveal fiery footprints; keep throwing and follow them to a cave.","Interact with the toy by the cave for a cutscene, then the altar inside; kill all the Ravagers."]},
{t:"Power-up statues",r:"7 free power-ups, then Fire Sale and a random perk",b:["Bonus Points: outside the Crash Site by a lamppost.","Insta-Kill: pillar top on the right of Scholar's Way, facing Machina Astralis.","Double Points: under a top-floor cabinet in Machina Astralis by the stairs.","Nuke: right of the Machina Astralis top balcony, seen from The Veilwalk.","Full Power: telescope platform, seen from Stargazer's Courtyard.","Max Armor: in a rock in Stargazer's Courtyard, left side from the Dome.","Max Ammo: top of the wall outside the map, left of the Luminarium trap room (from the Crash Site).","Fire Sale (after the 7): inside a Museum zombie window, left from Stargazer's Courtyard.","Random Perk (after all): by the ball on the right stair pillar, looking from Abyssal Rim toward the Luminarium."]},
{t:"Song: “Magic”",r:"Music (Avenged Sevenfold)",b:["Bottom of the bookshelf left of the Luminarium door to Abyssal Rim.","Display case in Machina Astralis.","Chair in the Observatory Dome."]},
{t:"Secret Pareidolia remaster",r:"Music",b:["On Mars, aim at the giant statue head to the right of the stairs (seen from the portal)."]},
{t:"Skull jumpscare",r:"Jumpscare",b:["After unlocking the telescope, use the binoculars left of the organ and aim at the small skull at RA 2h 23m, DEC 42° 21'."]}
],

relicNote:"Relics need this map's main quest done once and only drop in Cursed mode.",
relics:[
{n:"Seed",tier:"grim",e:"No Mystery Box.",trial:"Pack-a-Punch 1 pistol only.",u:["At round 20 a grey pistol (Jager, Velox or Coda) spawns. It can't be rarity-upgraded but can be PaP'd.","Kill exactly as many zombies with it as the round number, then finish the round with another gun. Portal: PaP room."]},
{n:"Gong",tier:"grim",e:"Field Upgrade starts charged but only refills from Full Power.",trial:"Zombies only take electric damage.",u:["Round 20: lightning-rod zombies appear (not on Ravager rounds). Bring one under a lightbulb, shoot it without killing to trigger Dead Wire, then Tesla Storm an orb into the bulb.","Bulbs: above the brain doorway; above the Stamin-Up exit toward the Mars portal; leaving PaP toward the spawn portal."]},
{n:"Spider Fang",tier:"sin",e:"Perk prices never drop.",trial:"No perks.",u:["Round 40+: kill an O.S.C.A.R. with a melee while your Wisp Tea wisp is still touching him."]},
{n:"Matryoshka Dolls",tier:"sin",e:"Salvage drop rate halved.",trial:"Only Field Upgrade kills count.",u:["Round 40+: kill zombies with C4 while they stand on the Mars center circle."]},
{n:"Civil Protector Head",tier:"wic",e:"Lose a perk every 100 kills.",trial:"Every zombie is a super sprinter.",u:["Round 60: four candles light in the chandeliers by Speed Cola. Throw an Energy Mine on Ol' Tessie — her headlights flash the order. Put each candle out by diving with PhD Flopper under it, in that order."]},
{n:"Golden Spork",tier:"wic",e:"Zombies deal double damage.",trial:"Only hip-fire damage counts.",u:["Round 60 (reported bugged and doable earlier): on Mars, shoot a Mangler cannon into the teleporter, teleport through and stand on the summoning circle; kill zombies in the circle with the Mangler shot."]}
],

intel:[
{k:"Audio log",n:"Fools",a:"The Luminarium",loc:"Metal shelf near the trap"},
{k:"Audio log",n:"Planets",a:"Observatory Dome",loc:"Back-corner shelf by a filing cabinet"},
{k:"Audio log",n:"Robotics",a:"Machina Astralis",loc:"Second-floor shelf"},
{k:"Audio log",n:"Dual Function",a:"The Veilwalk",loc:"Small gazebo near the ammo box"},
{k:"Document",n:"Immense Power",a:"The Luminarium",loc:"Shoot the planets in order from Mercury; Pluto drops and becomes the document"},
{k:"Document",n:"Eventful",a:"Archive of Orbis",loc:"Shoot a paper stack"},
{k:"Document",n:"Their Town",a:"Abyssal Rim",loc:"Fall off the map edge between Wisp Tea and the ammo box and interact"},
{k:"Artifact",n:"Damaged Drone",a:"Crash Site",loc:"Shoot down an O.S.C.A.R. drone"},
{k:"Artifact",n:"LGM-1",a:"Museum Infinitum",loc:"Build the Wonder Weapon"},
{k:"Artifact",n:"Perfusion Machine",a:"Machina Astralis",loc:"Main quest"},
{k:"Artifact",n:"Ascendant Eye",a:"Mars",loc:"Main quest"}
],

areas:["Crash Site","Abyssal Rim","The Luminarium","Stargazer's Courtyard","Observatory Dome","Scholar's Way","Machina Astralis","Museum Infinitum","Archive of Orbis","The Veilwalk","Mars"],
pins:[
{a:"Crash Site",c:"quest",n:"Car battery",d:"Shoot Ol' Tessie's hood with a PaP'd gun."},
{a:"Crash Site",c:"egg",n:"2 wisp lanterns",d:"Wisp Orbs → Ray Gun."},
{a:"Crash Site",c:"pu",n:"Bonus Points",d:"Outside by a lamppost."},
{a:"Abyssal Rim",c:"egg",n:"DG-2 asteroid",d:"Grenade the asteroid by Wisp Tea, wall-jump off it."},
{a:"Abyssal Rim",c:"egg",n:"Echoes of the Damned",d:"Nikolai: Molotov by the lower ammo cache."},
{a:"Abyssal Rim",c:"perk",n:"Wisp Tea",d:"Needed for Spider Fang."},
{a:"The Luminarium",c:"ww",n:"Electro-Volt Projector",d:"Behind Juggernog; also the brain container."},
{a:"The Luminarium",c:"perk",n:"Gramophone (Field Upgrade kills)",d:"Record on a bookshelf by the clock."},
{a:"The Luminarium",c:"quest",n:"Neptune page",d:"Desk in the trap room."},
{a:"The Luminarium",c:"music",n:"Headset 1",d:"Bookshelf bottom left of the door to Abyssal Rim."},
{a:"Stargazer's Courtyard",c:"pu",n:"Max Armor",d:"In a rock, left side from the Dome."},
{a:"Stargazer's Courtyard",c:"egg",n:"Skull",d:"Spawn hole by the ammo cache."},
{a:"Observatory Dome",c:"quest",n:"PaP / organ / telescope",d:"Sunbeam trap, code machine, organ symbols."},
{a:"Observatory Dome",c:"music",n:"Headset 3",d:"On a chair."},
{a:"Observatory Dome",c:"egg",n:"Skull jumpscare",d:"Binoculars left of the organ."},
{a:"Scholar's Way",c:"pu",n:"Insta-Kill",d:"Pillar top facing Machina Astralis."},
{a:"Scholar's Way",c:"egg",n:"2 wisp lanterns",d:"Wisp Orbs."},
{a:"Machina Astralis",c:"quest",n:"Cryo capsule / planetarium",d:"Brain, keypad, orrery; Saturn page on the 2nd floor."},
{a:"Machina Astralis",c:"egg",n:"Skull cabinet",d:"Place the five skulls on the large-mirror cabinet."},
{a:"Machina Astralis",c:"music",n:"Headset 2",d:"Display case."},
{a:"Machina Astralis",c:"pu",n:"Double Points / Nuke",d:"Under a top-floor cabinet; right of the top balcony."},
{a:"Museum Infinitum",c:"ww",n:"Rocket trap",d:"In front of Speed Cola."},
{a:"Museum Infinitum",c:"quest",n:"Hacksaw",d:"Display case left of the Speed Cola door."},
{a:"Museum Infinitum",c:"perk",n:"Gramophone (melee kills)",d:"Record above a zombie window."},
{a:"Museum Infinitum",c:"egg",n:"Twins cabinet",d:"Left-most cabinet under the castle painting."},
{a:"Archive of Orbis",c:"quest",n:"Library busts → Neptune",d:"Mars page on the middle desk."},
{a:"Archive of Orbis",c:"perk",n:"Gramophone (equipment kills)",d:"By Stamin-Up."},
{a:"The Veilwalk",c:"egg",n:"Skull",d:"Behind the brick wall."},
{a:"Mars",c:"quest",n:"Pylons, Ascendant Eye, pillars",d:"Final puzzles and the boss."},
{a:"Mars",c:"relic",n:"Matryoshka / Golden Spork",d:"Center circle; summoning circle."},
{a:"Mars",c:"music",n:"Pareidolia remaster",d:"Aim at the statue head right of the stairs."}
],

toy:{name:"Caltheris",prep:"Longest toy quest. Needs the LGM-1, telescope, Mars, the DG-2 on Ol' Tessie, explosives, a Kazimir and two Shock Charges.",
 steps:[["Bring the toy box in","It floats outside the map around the corner from the Arsenal near Juggernog. Explode it to push it until it stops near spawn (Crash Site), then pull it down with a Kazimir.",[["Toy box",SK("6ab29192b2d240.58312393")]]],
  ["DG-2 + O.S.C.A.R.","Mount the DG-2 (space trip side egg) on Ol' Tessie and kill O.S.C.A.R. with it while he's near the box. The box opens.",[["DG-2",SK("6ab291a8a4a425.85488406")]]],
  ["Shooting star, then UFO","Find a shooting star in the PaP telescope. Do Time Dilation (five clocks), then find the UFO in the telescope and hold your crosshair on it.",[["Star",SK("6ab291dbd121a8.14175234")]]],
  ["Gold wisps","Do the nine-lantern Wisp Orbs side egg and carry at least four gold wisps.",[]],
  ["Morse code on Mars","Progress the main quest to Mars (stop before the boss). Throw Shock Charges on the two disks at the back of Mars to summon the UFO. Its Morse code spells the first letters of the four objects (Flamingo, Toilet, Space suit, Lava lamp); melee a wisp into each in that order.",[["UFO",SK("6ab291f9e0c870.81713223")],["Objects",SK("6ab2920dd353b3.33813640")]]],
  ["Claim and exfil","An alien drops. Put it in the box for the Caltheris toy, then exfil.",[["Caltheris toy",SK("6ab2921ceff999.16843435")]]]]},
codes:"astra",
src:[["MargwaNetwork — Astra Malorum","https://margwa.net/astra-malorum"],["BO7 Easter Eggs (Google Doc)","https://docs.google.com/document/u/0/d/1zFsG8A0BA_jUt8BNoAd2lmw36OR35ecOzicHwoXsexw/mobilebasic"],["Skycoach — main quest","https://skycoach.gg/blog/call-of-duty/articles/black-ops-7-zombies-astra-malorum-main-quest-guide"],["Skycoach — Super EE","https://skycoach.gg/blog/call-of-duty/articles/super-easter-egg-guide"]]
});
