MAPS.push({
id:"kowa", slug:"kowakujo", name:"Kowakujō", color:"#d8442f", season:"Season 4 Reloaded", date:"Jun 25, 2026",
blurb:"Takeo's family castle in a volcanic Dark Aether. Lava scorches zombies into tougher versions, Oni stalk the courtyards, and the main quest is a full murder mystery.",
ww:"Nekomancer (PaP: Tsunderera-Hime)", boss:"Nyxara the dragon", reward:"“Purified” Takeo skin + calling card",
mapImg: MGMAP("kowakujo"),

wwInfo:{what:"A spirit cat that fires explosive hairballs. Rescuing it takes a cage, a lucky cat charm, a paw-print trail and a very quiet sneak.",
 steps:["Buy PhD Flopper. Dive-prone beside the hanging cage at Tenshu Entrance (by the cherry tree) to knock it down. Throw it into lava; flip the round.","Collect the Furin bell (listen in Staging, Training or Stables), the Maneki-Neko statue (Kitchens barrels or Gatehouse) and the Karakuri doll (Storage Rooms or Workshop). Craft at the Workshop table left of Vulture Aid.","Kill zombies at Stables, Kitchens or Flower Garden gateways until orange paw prints appear. Follow them until they form a circle; throw the Maneki-Neko in the middle while the lava is hot.","Kill the Abomination that eats the cat (shoot its open mouths). Flip the round.","With Death Perception, crouch-walk to the cat on the creaky floors (Training Grounds or two Kitchens spots) without stepping on glowing boards. Pick it up.","At the World Seed in Shogun's Sanctum, melee between shockwaves until the cat jumps free. That's the Nekomancer."],
 tips:["No sprinting, shooting or field upgrades near the cat — it runs and you check again next round.","The Valkyrie Helmet relic needs the Nekomancer's charged-shot bubble, so build it before chasing that relic."]},

speedIntro:"Kowakujō's murder mystery has a few pieces you can grab any time. The speed route picks them up early so the evidence board never waits on them.",
steps:[
{id:"k1",t:"Pack-a-Punch",loc:"Outer Ward → Training Area & Kitchens → War Room → Shogun's Sanctum",b:["Recapture two Wards by standing in their circles (Training Area, Kitchens; any order).","Remove the Gate Glyphs in the Central Courtyard, push to the War Room, kill the Oni for Shogun's Hanko.","Use it on the golden dragon door. In Shogun's Sanctum, kill the purple-marked zombies by the World Seed — Pack-a-Punch appears."],ph:[["Start",SK("6a3d66ba05fee4.64871794")],["War Room",SK("6a3d66dedc0aa0.21658401")]]},
{id:"k2",t:"Cage into lava",loc:"Tenshu Entrance",b:["With PhD Flopper, dive-prone beside the suspended cage by the cherry tree. Throw the cage into any lava. Flip the round."],ph:[["Cage/lava",SK("6a3e20c7e91ec3.19625245")]]},
{id:"k3",t:"Craft the Maneki-Neko",loc:"Workshop",b:["Furin bell (Staging/Training/Stables — follow the ringing), cat statue (Kitchens barrels or Gatehouse barrel), Karakuri doll (Storage Rooms or Workshop). Craft at the table left of Vulture Aid. It's a tactical — don't waste it."]},
{id:"k4",t:"Paw prints → Abomination",loc:"Stables / Kitchens / Flower Garden",b:["Kill zombies at gateways until orange paw prints show in the blood; keep killing in the direction they face until they form a circle.","Throw the Maneki-Neko into the center while the lava is active. Kill the Abomination that swallows the cat (shoot open mouths). Flip the round."]},
{id:"k5",t:"Sneak up on the cat",loc:"Training Grounds or Kitchens",b:["Death Perception highlights creaky boards. Crouch-walk around them and pick up the cat."],ph:[["Cat",SK("6a3e225a297fc7.89737406")]]},
{id:"k6",t:"Free the cat → Nekomancer",loc:"Shogun's Sanctum",b:["The cat hops on the World Seed. Melee the seed between its shockwaves until the cat jumps down; take the Nekomancer."],ph:[["Nekomancer",SK("6a3d67d6e6b596.22098431")]]},
{id:"k7",t:"Light 11 lanterns",loc:"Whole map (timed)",b:["Shoot them with the Nekomancer in any order once the timer starts. Locations in the Codes tab."]},
{id:"k8",t:"War Room spirit",loc:"War Room",b:["Interact with the spirit corpse with the katana for a cinematic (the “Takeo's Resolve” audio log spawns). Check the spot for a Ceramic Shard."]},
{id:"k9",t:"Fox Mask",loc:"Roof kite → Storage Rooms",b:["Take the Ninja Kite toward the big cherry tree, hold right and spam interact to grab the mask on the right-side roof edge.","Place it on the mask wall in the Storage Rooms (PhD side)."]},
{id:"k10",t:"Mask Simon Says",loc:"Storage Rooms",b:["Masks glow in sequence; kill zombies wearing those masks in the same order. Rounds of 3, 4 and 5. Wrong kill = next round. Avoid explosives; do it with one zombie left."],ph:[["Mask wall",SK("6a421d521708c0.64554085")]]},
{id:"k11",t:"Suspect evidence → painting 1",loc:"Workshop · Collapsed Study · Onsen Baths",b:["Shoot the flying mask at each hideout: Takeshi's Pipe (Workshop shelf left of stairs), Takeo's Case (Collapsed Study beam by the ceiling), Mitsuhime's Comb (outside the Onsen window left of Elemental Pop — aim top-left).","Place them on the Meditation Room shelves."]},
{id:"k12",t:"Coin Purse",loc:"Tagged Mystery Box spot → Outer Ward",b:["One Mystery Box platform has a small wooden tag. Get the box there (spin, Fire Sale…), throw a Maneki-Neko on/in front of it and spin for a blue Coin Purse.","Interact with the ghostly coin pouch at the back of spawn by the Rampage Inducer."]},
{id:"k13",t:"Gardener → Gardening Shears",loc:"Flower Garden",b:["Bucket spawns: Cat Cafe (Tea Garden), Onsen roof, behind Speed Cola (Gatehouse), left of Death Perception (Stables). Fill it at the Tea Garden puddle or Onsen pool; no sprinting, jumping or getting hit.","Water three weeds on the cobblestone path. The Gardener is immune until you shoot the glowing flower pots."],ph:[["Gardener",SK("6a421ecca6b6d7.12215811")]]},
{id:"k14",t:"Merchant → Mercantile Abacus",loc:"Kitchens → Staging Area",b:["Melee the Kitchens fruit basket, leave the fruit, come back after 60–90 s. Lead the zombie holding it to the shack window between the Stables and Courtyard entrances and kill it there. Kill the Merchant who climbs out."]},
{id:"k15",t:"Nobleman → Nobleman's Hat (painting 2)",loc:"Training Area",b:["Throw Decoys at the three shuttered windows above the gate in quick succession. Cook the blue grenades thrown at you and throw them back at whichever window holds the Nobleman.","Place shears, abacus and hat (with notes) in the Meditation Room."]},
{id:"k16",t:"Poison evidence → painting 3",loc:"War Room · Flower Garden · Kitchens · Storage",b:["Take the Poison Compendium from the War Room shelf.","<b>Monkshood:</b> plant part by the Flower Garden crack → flower pot by the Tenshu exfil phone. Knock the Empty Pouch off the Training Area gate beam with a charged Nekomancer; fill it with Volcanic Ash during a Fissure (stand in the ash). Add it to the pot, get the cherry-tree overheal and run circles by the pot until it blooms.","<b>Plum Pit:</b> melee the Kitchens basket by the fire pit and jump on the plum.","<b>Pufferfish:</b> after painting 2, solve the 3×3 scroll toggle puzzle in Storage Rooms for the Pestle. Put it in the Kitchens bowl, feed it Brain Rot kills, then take the Pufferfish from the cupboard area."],ph:[["Poison",SK("6a4220932a2270.52299950")],["Monkshood",SK("6a4220b550d0a3.58997719")],["Pufferfish",SK("6a42224de2a384.48227283")]]},
{id:"k17",t:"Ceramic cup → painting 4",loc:"Tea Garden → three defenses",b:["Take the shard from painting 3 plus the War Room/PaP-stairs shard. Repair the cup at the Tea Garden Kintsugi station; next round take it.","Defend it: War Room → Horse Statuette; Collapsed Study → Calligraphy Brush; Cat Cafe → a hellhound steals it, kill it for the Tea Whisk."]},
{id:"k18",t:"Netsuke of Brothers",loc:"Stables",b:["When the lava cools, a small glowing statue sits on it. Knock it loose with a Molotov or explosive and pick it up."]},
{id:"k19",t:"Clock and flags → Crest Medallion (painting 5)",loc:"Storage Rooms → Staging → 4 symbols",b:["Clock (bottom of Storage Rooms, PhD side) shows four numbers. Flip the round; kill the flag-carriers in the assault wave.","Each flag is worth its symbol count. Plant flag totals matching the clock at the four numbered symbols (spawn, Flower Garden by Wisp Tea, Central Courtyard, Stables roof) in the symbols' order. Then take the medallion from the clock."],ph:[["Clock & flags",SK("6a4223f76260c6.51673660")]]},
{id:"k20",t:"Trap ghost clue",loc:"Oni / archer traps",b:["Get 15–20 kills in a single trap activation, then talk to the ghost soldier (subtitles on). He names the accomplice — or nothing; try another trap.","The Google doc pairs the traps with suspects: Flower Garden trap → Nobleman, castle trap → Gardener, spawn trap → Merchant."]},
{id:"k21",t:"Solve the murder board",loc:"Meditation Room",b:["Place one item under each painting and set the zodiac dial (Codes tab has the full table and a dial helper). Light the incense on both sides. Wrong = elite spawns; retry next round.","Getting it right on the first try also gives the Path of Sorrows after the boss (needed for the Dragon Egg relic)."],ph:[["Board",SK("6a42250b1eb3b9.19333421")]]},
{id:"k22",t:"Purify the sword → Oni fight",loc:"World Seed → Central Courtyard",b:["Interact with the sword at the World Seed to fight a stronger Oni. A new kite to the boss appears afterwards — entering is one-way."]},
{id:"k23",t:"Optional: upgraded Neko grenades",loc:"Tenshu Entrance · Kitchens",b:["First do the upgraded-trap step: shoot a blue target at the Tenshu Entrance trap with a Combat Bow.","Collect the white powder by the Tenshu Entrance tree, the Matches from a barrel bookshelf in the Kitchens and coal from the Kitchen stove. Craft at the Maneki-Neko table — the grenades now make a protective bubble. Anyone already holding a Maneki-Neko gets the upgrade automatically."]},
{id:"k24",t:"Boss: Nyxara",loc:"Boss kite",b:["Kill the flag-carrying Oni, plant the flag, capture the zone. Stand in the blue safe zone and shoot the glowing weak spots.","Phase 2 needs two zones; phase 3 needs three. Watch for lava strips, electric tornadoes and fireballs; weak spots move to the wings late."],ph:[["Nyxara",SK("6a42286ee6cdc1.66486242")]]}
],
speed:["k1","k2","k3","k4","k5","k6","k18","k7","k8","k9","k10","k11","k12","k13","k14","k15","k16","k20","k17","k19","k21","k23","k22","k24"],
speedNotes:{k2:"Hunt the three Maneki-Neko parts while you wait for the round to flip.",k18:"Knock the Netsuke loose whenever you see the Stables lava cool — it's only needed at the very end.",k16:"Start the Monkshood and Plum Pit as soon as the Accomplice steps are underway; only the Pufferfish waits on painting 2.",k20:"Farm the ghost clue during any trap activation along the way.",k23:"Do the Neko upgrade before the Oni fight — the boss kite is one-way."},

side:[
{t:"Neko-Café",r:"Three free random perks (and the map challenge)",b:["Collect 5 mice (they spawn from the start) and scare 5 cats. A new cat appears every 1–3 rounds; 5 of these 8 spots are used each game:","Gatehouse (barrier across from the wall-buy) · Flower Garden (barrier between GobbleGum and the Mystery Box) · Kitchens (barrier by the pots) · Stables (rafters across from the wall-buy) · Training Area (rafters by the crafting table) · Tenshu Entrance (fence near exfil) · Onsen Baths (rafters near the wall-buy) · Central Courtyard (near Juggernog).","Scared cats sit on the Tea Garden building and mice gather on the shelf by the bucket. With all ten, the café opens."]},
{t:"Free power-up statues",r:"7 free power-ups, then a Fire Sale and a free perk",b:["Shoot each icon:","<b>Bonus Points:</b> Kitchens, above the wall-buy.","<b>Double Points:</b> Collapsed Study, on a tree.","<b>Nuke:</b> Training Area, in the lava against the wall.","<b>Full Power:</b> Flower Garden, in a sunken house.","<b>Max Armor:</b> Workshop, next to a chest.","<b>Insta-Kill:</b> Storage Rooms, next to GobbleGum.","<b>Max Ammo:</b> Training Area, by a lantern on the ground.","<b>Fire Sale</b> (after the first 7): Onsen Baths, in the puddle.","<b>Perk</b> (after all others): Kitchens, near the Pufferfish spawn."]},
{t:"Lava-rock parkour",r:"Ray Gun + calling card (repeatable)",b:["About every 15 minutes a rock floats up in the lava near Melee Macchiato.","Ride it to the broken house and jump onto the house. Walk to the northern edge to start a timed obstacle course; finish it in time."]},
{t:"Mecha-Klaus",r:"“Mecha Mayhem” Dark Ops calling card; Klaus then sells a Rhino scorestreak",b:["Shoot the floating rocks in the lava pools for Klaus parts — two arms, then two legs.","After the second leg, his body appears in the Flower Garden near Wisp Tea. Interact to spawn a Klaus Core and destroy it.","Interact with the body again to start a kaiju fight against a Zursa and an Abomination. Win it."]},
{t:"Horse race",r:"Paper Horse companion (repeatable)",req:"Whole map open",b:["Collect four carrots: Outer Ward (near Quick Revive), Flower Garden (near exfil), Kitchens (by the Green Plum, under the cabbages), Workshop (down the stairs from the crafting table, in a bucket).","Interact with the Stables bucket that has a paper horse above it (near the Mystery Box) and finish the race in time."]},
{t:"Gacha machine",r:"500-salvage spins; the Pufferfish charm drops overhealing fruit",b:["Melee a cherry (Sakura) tree three times for Flower Power, then step into an active fissure while overhealed.","Melee the gacha machine (known spawn: Kitchens) and jump through every orb that appears to place it permanently. Spin it for 500 salvage."]},
{t:"Takeo Flashback",r:"Scorestreaks, Intel by Pack-a-Punch, and a higher-rarity katana",req:"Takeo operator · Psyche Grenade · once per game",b:["In the War Room, pick up the two katanas.","Throw a Psyche Grenade at your feet, find ghostly Takeo and walk up to him for his katana. Dying or falling off the path ends it. Round 1 works."]},
{t:"Upgraded trap (Tenshu Entrance)",r:"Ammo-mod rewards — up to 4 upgrades",req:"Combat Bow scorestreak",b:["At the Tenshu Entrance trap, shoot the blue targets through each phase with the Combat Bow (the first hit triggers Aether Shroud).","Repeat up to four times. The first completion also unlocks the upgraded Maneki-Neko."]},
{t:"Upgraded Maneki-Neko",r:"Maneki-Neko grenades that make a protective bubble",req:"First upgraded-trap step done",b:["White powder by the Tenshu Entrance tree, Matches from a barrel bookshelf in the Kitchens, coal from the Kitchen stove.","Craft at the crafting table. Anyone already holding a Maneki-Neko is upgraded automatically."]},
{t:"Ninja Kites",r:"Fast travel",b:["From the Tenshu rooftops, 500 essence per ride. Collect the floating soul points mid-flight to earn the cost back."]},
{t:"Song: “Evencry”",r:"Music",b:["Headset 1: in a Kitchens barrel.","Headset 2: Stables, behind rubble.","Headset 3: Onsen Baths, on a shelf by the puddle."]}
],

relicNote:"Relics need this map's main quest done once. Kowakujō's Cursed mode also awards Flame, Toxic and Blood Cipher PaP camos by tier.",
relics:[
{n:"Gramophone",tier:"grim",e:"Bullets hit harder but each shot uses 2 rounds.",trial:"Enemies can only be damaged by sniper rifles.",u:["Collect two drumsticks: one in the Gatehouse, one in the Workshop.","Interact with the drums on the stairs from the Flower Garden to the Kitchens and repeat the Simon Says drum pattern three times. The portal spawns."]},
{n:"Druid Stone",tier:"grim",e:"No bleed-out bar; Self-Revive Kits revive instantly.",trial:"Enemies can only be damaged while you're overhealed.",u:["Reach round 20 without taking any enemy damage (lava damage is allowed)."]},
{n:"Valkyrie Helmet",tier:"sin",e:"Staying in one area spawns electric fields that hurt you.",trial:"Reloading makes you explode.",u:["Upgrade the Maneki-Neko and build the Nekomancer.","Make a bubble with a charged shot, kill zombies inside it; each bubble break drops a plate fragment. Collect four.","Put the fragments by the fire pit near the Pufferfish and Molotov them to craft a plate.","Finish the Neko-Café and take catnip from a cat tower.","Place the catnip and plate on the rock by the big cherry tree in the Central Courtyard. Fail assault waves until one spawns there, then get about 50 Nekomancer kills while staying in it."]},
{n:"Film Reel",tier:"sin",e:"Only one Pack-a-Punched weapon at a time.",trial:"Zombies can only die to the assigned scorestreaks.",u:["Pack-a-Punch 10 different weapons."]},
{n:"Dragon Egg",tier:"wic",e:"Elites and specials in normal rounds are randomized.",trial:"Survive Mister Peeks' 6 tiers of insanity.",u:["Solve the murder mystery right on the first try so the Path of Sorrows spawns after the boss.","Make an Oni fire its charged attack and parry it with the Path of Sorrows.","While the sword is electrified, melee three symbols in order: <b>姿</b>, <b>を</b>, <b>見世</b>."]},
{n:"Mannequin Turret",tier:"wic",e:"No starting armor; only the gold wall-buy armor.",trial:"No health regen; you fully heal at the end of each wave.",u:["Reach round 60 without failing a single assault wave."]}
],

intel:[
{k:"Audio log",n:"Takeo's Resolve",a:"War Room",loc:"Main quest — after the cutscene following the lantern step"},
{k:"Audio log",n:"Takeo's Devotion",a:"Kitchens",loc:"Main quest — after the Sake Cup soul box"},
{k:"Audio log",n:"Takeshi's Dread",a:"Outer Ward",loc:"Main quest — after placing the Coin Purse at spawn"},
{k:"Audio log",n:"Takeshi's Perception",a:"Tea Garden",loc:"Main quest — after repairing the Sake Cup"},
{k:"Audio log",n:"Mitsuhime's Trepidation",a:"Storage Rooms",loc:"Main quest — after placing the 4th evidence, by the clock"},
{k:"Audio log",n:"Mitsuhime's Reverence",a:"Storage Rooms",loc:"After Mask Simon Says, on the shelf left of the masks"},
{k:"Audio log",n:"Katanas Out",a:"War Room",loc:"Takeo Flashback side egg"},
{k:"Audio log",n:"Two Brothers",a:"Outer Ward",loc:"On a bridge post near the ammo box and trap",ch:"A Bridge Too Far"},
{k:"Audio log",n:"Paydirt",a:"Flower Garden",loc:"Behind the large rock between the exfil booth and Wisp Tea",ch:"Between a Rock and a Hot Place"},
{k:"Audio log",n:"Subverting Control",a:"Training Area",loc:"On a box in the corner",ch:"Training Montage"},
{k:"Audio log",n:"Extra Crispy",a:"Collapsed Study",loc:"Behind the armor buy — interact with the pizza",ch:"Pie in the Sky"},
{k:"Audio log",n:"What About the Cat",a:"Storage Rooms",loc:"Table beside a lantern (needs Extra Crispy first)",ch:"Ready to Scroll"},
{k:"Document",n:"Psspsspss",a:"Kitchens",loc:"Interact with a barrel near Double Tap (random barrel each game)",ch:"Barrel of Laughs"},
{k:"Document",n:"Hair Raising",a:"Shogun's Sanctum",loc:"Tenshu rooftops — melee the scrolls on the shelf",ch:"Raising the Roof"},
{k:"Artifact",n:"Ninja Kite",a:"Shogun's Sanctum",loc:"Glide on a kite for the first time"},
{k:"Artifact",n:"Maneki-Neko",a:"Workshop",loc:"Build the Maneki-Neko tactical"},
{k:"Artifact",n:"Nekomancer",a:"Shogun's Sanctum",loc:"Build the Wonder Weapon"},
{k:"Artifact",n:"Kitsune Mask",a:"Storage Rooms",loc:"Grab the Fox Mask"},
{k:"Artifact",n:"Lantern Clock",a:"Storage Rooms",loc:"Interact with the clock"},
{k:"Artifact",n:"Path of Sorrows",a:"Shogun's Sanctum",loc:"After the boss, if the murder mystery was solved first try"}
],

areas:["Outer Ward","Staging Area","Training Area","Stables","Kitchens","Flower Garden","Gatehouse","Workshop","Storage Rooms","Collapsed Study","Onsen Baths","Tea Garden","Central Courtyard","Tenshu Entrance","War Room","Meditation Room","Shogun's Sanctum"],
pins:[
{a:"Outer Ward",c:"quest",n:"Ghostly coin pouch",d:"Back of spawn by the Rampage Inducer."},
{a:"Outer Ward",c:"egg",n:"Carrot 1",d:"Near Quick Revive."},
{a:"Staging Area",c:"quest",n:"Shack window",d:"Kill the fruit zombie here for the Merchant."},
{a:"Training Area",c:"quest",n:"Shuttered windows / pouch beam",d:"Nobleman decoys; Empty Pouch."},
{a:"Training Area",c:"pu",n:"Nuke / Max Ammo",d:"In the lava by the wall; by a lantern on the ground."},
{a:"Stables",c:"quest",n:"Netsuke on cooled lava",d:"Molotov it loose."},
{a:"Stables",c:"egg",n:"Paper-horse bucket",d:"Horse race start, near the Mystery Box."},
{a:"Stables",c:"music",n:"Headset 2",d:"Behind rubble."},
{a:"Kitchens",c:"quest",n:"Fruit basket / plum / pestle bowl",d:"Merchant, Plum Pit and Pufferfish."},
{a:"Kitchens",c:"egg",n:"Gacha machine / Neko upgrade",d:"Matches (barrel bookshelf) and coal (stove)."},
{a:"Kitchens",c:"pu",n:"Bonus Points / Perk",d:"Above the wall-buy; near the Pufferfish spawn."},
{a:"Kitchens",c:"music",n:"Headset 1",d:"In a barrel."},
{a:"Kitchens",c:"relic",n:"Drum stairs",d:"Gramophone pattern (stairs from the Flower Garden)."},
{a:"Flower Garden",c:"quest",n:"Gardener weeds",d:"Water three weeds; shoot glowing pots."},
{a:"Flower Garden",c:"egg",n:"Mecha-Klaus body",d:"Near Wisp Tea."},
{a:"Flower Garden",c:"pu",n:"Full Power",d:"In a sunken house."},
{a:"Gatehouse",c:"relic",n:"Drumstick 1",d:"Gramophone relic."},
{a:"Workshop",c:"ww",n:"Crafting table",d:"Left of Vulture Aid — Maneki-Neko."},
{a:"Workshop",c:"relic",n:"Drumstick 2",d:"Gramophone relic."},
{a:"Workshop",c:"pu",n:"Max Armor",d:"Next to a chest."},
{a:"Storage Rooms",c:"quest",n:"Mask wall / clock / scroll puzzle",d:"Simon Says, flags clock, Pestle."},
{a:"Storage Rooms",c:"pu",n:"Insta-Kill",d:"Next to GobbleGum."},
{a:"Collapsed Study",c:"pu",n:"Double Points",d:"On a tree."},
{a:"Onsen Baths",c:"pu",n:"Fire Sale",d:"In the puddle (after 7)."},
{a:"Onsen Baths",c:"music",n:"Headset 3",d:"Shelf by the puddle."},
{a:"Tea Garden",c:"egg",n:"Neko-Café",d:"Cats on the roof; mice on the shelf."},
{a:"Tea Garden",c:"quest",n:"Kintsugi station",d:"Repair the ceramic cup."},
{a:"Central Courtyard",c:"relic",n:"Cherry-tree rock",d:"Valkyrie Helmet plate + catnip."},
{a:"Central Courtyard",c:"quest",n:"Big cherry tree",d:"Super EE origami bird."},
{a:"Tenshu Entrance",c:"ww",n:"Hanging cage",d:"PhD dive to drop it."},
{a:"Tenshu Entrance",c:"egg",n:"Upgradable trap / white powder",d:"Combat Bow targets; Neko upgrade powder."},
{a:"War Room",c:"egg",n:"Two katanas",d:"Takeo Flashback."},
{a:"Meditation Room",c:"quest",n:"Murder board",d:"Paintings, evidence and zodiac dial."},
{a:"Shogun's Sanctum",c:"ww",n:"World Seed",d:"Pack-a-Punch and freeing the cat."}
],

toy:{name:"Z-Rex",prep:"One of the fastest toys. Just open the map and turn on Pack-a-Punch.",
 steps:[["Tornado the toy box down","Melee the cherry tree near PaP until it activates and stand by it for the overheal glow. Go under the floating toy box on the rooftops and run in circles until a tornado knocks it down. A bird flies out.",[["Toy box",SK("6ab292ff115b39.79053548")]]],
  ["Guide the bird","Activate cherry trees in order — Kitchens, Staging Area, Training Area — waiting for the bird to land at each. Re-buff at a tree if you lose the overheal.",[]],
  ["Origami bird","With the overheal, run circles around the stump by the big Central Courtyard tree until a tornado sends the bird to the tree. A glowing origami bird drops.",[["Origami",SK("6ab2930f1a7c50.78590772")]]],
  ["Claim and exfil","Put it in the toy box for loot and the Z-Rex toy, then exfil.",[]]]},
codes:"kowa",
src:[["MargwaNetwork — Kowakujō","https://margwa.net/kowakujo"],["BO7 Easter Eggs (Google Doc)","https://docs.google.com/document/u/0/d/1zFsG8A0BA_jUt8BNoAd2lmw36OR35ecOzicHwoXsexw/mobilebasic"],["Skycoach — main quest","https://skycoach.gg/blog/call-of-duty/articles/kowakujo-easter-egg-guide"],["Skycoach — Super EE","https://skycoach.gg/blog/call-of-duty/articles/super-easter-egg-guide"]]
});
