MAPS.push({
id:"rex", slug:"rex-infernus", name:"Rex Infernus", color:"#9a5ce0", season:"Season 5 Reloaded", date:"Aug 20, 2026",
blurb:"The final map: the Warden's domain in the Dark Aether. A ring of Shadowsmith temples around the Nexus Forge, Void Claw grapples, and spiders that web you in place.",
ww:"Warden's Blight (dual crossbows)", boss:"The Warden", reward:"Bloodthorn WW skin + calling card",
mapImg: MGMAP("rex-infernus"),

wwInfo:{what:"Dual crossbows. Pack-a-Punched, they gain a charged alt-fire that several quest steps require.",
 steps:[
 {t:"Void Claw → Fracture of Nyxara",loc:"Dravakar's Entrance · ledge above the door",b:["Take a Void Claw (grapple) from any green-flame pedestal. It refills at any lit green flame.","Climb the stairs and grapple or wall-jump onto the small platform above Dravakar's entrance door. Turn right and break the wall there with an explosive or a PhD dive to reveal the Fracture of Nyxara. Pick it up."],
  ph:[["Void Claw pedestal",CZ("rex-infernus","void-claw-pedestal"),CZQ("rex-infernus")],["Hidden alcove above the door","https://www.dexerto.com/cdn-image/wp-content/uploads/2026/08/20/Jump-to-reach-hidden-alcove-COD-1.jpg?width=1200&quality=50&format=auto","https://www.dexerto.com/wikis/black-ops-7-guides-walkthrough-tips/how-to-get-the-wardens-blight-wonder-weapon-in-rex-infernus/"],["Fracture of Nyxara",CZ("rex-infernus","fracture-of-nxyara"),CZQ("rex-infernus")]]},
 {t:"Slot the Fracture",loc:"Nyxara Main Chamber · wall above the ammo crate",b:["Grapple up and place the Fracture in the empty pedestal on the wall above the ammo crate."],
  ph:[["Pedestal",CZ("rex-infernus","nxyara-main-chamber-pedestal"),CZQ("rex-infernus")]]},
 {t:"Make Astral Flame",loc:"Nexus Forge · Pack-a-Punch fountain",b:["Look up around the Nexus Forge for a floating purple orb. Grapple it toward the center over and over until it starts circling the fountain.","Turn the crank on the fountain (like the Pack-a-Punch quest). Astral Flame appears in a brazier above; interact to take it. Each flame is single-use, so keep spares in the braziers."],
  ph:[["Purple orb",CZ("rex-infernus","purple-orb"),CZQ("rex-infernus")],["Astral Flame",CZ("rex-infernus","astral-flame"),CZQ("rex-infernus")]],q:["r2"]},
 {t:"Steer the beam → Inner Sanctum",loc:"Nyxara Sanctuary → Nyxara Main Chamber",b:["Throw the Astral Flame at the big eye on the Sanctuary's back wall. The flame starts bouncing between crystals.","Grapple a crystal to rotate it so the beam hits the next one. Do this for three crystals until the beam reaches the locked door in Nyxara's Main Chamber.","The door's veil dissolves. Step up to the purple orb inside; the floor gives way into the Inner Sanctum."],
  ph:[["Sanctuary eye",CZ("rex-infernus","nxyara-sanctuary-eye"),CZQ("rex-infernus")],["Grappling a crystal","https://www.dexerto.com/cdn-image/wp-content/uploads/2026/08/20/Grappling-the-beam-in-COD.jpg?width=1200&quality=50&format=auto","https://www.dexerto.com/wikis/black-ops-7-guides-walkthrough-tips/how-to-get-the-wardens-blight-wonder-weapon-in-rex-infernus/"],["Inner Sanctum",CZ("rex-infernus","nxyara-inner-sanctum"),CZQ("rex-infernus")]],q:["r5"]},
 {t:"Eat the vine fruit → the Forest's three parts",loc:"Nyxara Inner Sanctum → the Forest",gate:"Round 8+",b:["The vine drains your health until its bar is full. Then interact to eat the fruit and you're pulled into the Forest (Whispers of the Past). The fruit won't grow before round 8.","Each part sits by a charred body or under a floorboard; interacting plays a short cutscene. You need all three, in any order. The Forest is timed: if you're thrown out (or die), feed the vine again next round and get the rest.","The Forest layout can be mirrored, so the cave and cabin may be on the far left or the far right."],
  spots:[{h:"Blight parts · collect all three",list:[["Bow · body in the cave (far left or far right)",CZ("rex-infernus","warden-blight-bow"),CZQ("rex-infernus")],["Stock · body leaning on the rock in the middle",CZ("rex-infernus","warden-blight-stock"),CZQ("rex-infernus")],["Handles · melee the floorboards of the broken cabin (far left or far right)",CZ("rex-infernus","warden-blight-handles"),CZQ("rex-infernus")],["All three bodies side by side","https://gameshorizon.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-21-at-4.55.30-PM-2-1024x576.jpeg","https://gameshorizon.com/guides/bo7-zombies-rex-infernus-how-to-get-wardens-blight-wonder-weapon/"]]}],
  ph:[["Vine fruit",CZ("rex-infernus","vine-fruit"),CZQ("rex-infernus")]],q:["r6"]},
 {t:"Dravakar's riddle",loc:"Dravakar Sanctuary",b:["Walk up to the blue writing on the wall; it speaks one of four phrases. The phrase sets how many times to press each of the three switches. The <b>Codes</b> tab has the presses for every phrase.","Set the switches, then pull the confirm switch on the center pillar. A wrong answer means waiting a round."],
  spots:[{h:"Riddle switches",list:[["Blue writing (the riddle)",CZ("rex-infernus","dravakar-sanctuary-text"),CZQ("rex-infernus")],["Switch on the wall, left of the blue writing",CZ("rex-infernus","dravakar-middle-switch"),CZQ("rex-infernus")],["Switch on the north-west wall",CZ("rex-infernus","dravakar-northwest-switch"),CZQ("rex-infernus")],["Switch on the south-east wall",CZ("rex-infernus","dravakar-southeast-switch"),CZQ("rex-infernus")],["Confirm switch · center pillar",CZ("rex-infernus","dravakar-sanctuary-switch"),CZQ("rex-infernus")]]}]},
 {t:"Forge the Warden's Blight",loc:"Dravakar's Secret Passage → Forge Room",b:["If the answer was right, the center platform lowers, the screen flashes white and a hole opens in the ceiling.","Grapple up through it, interact with the anvil and take the Warden's Blight. Pack-a-Punch it right away."],
  ph:[["Warden's Blight",CZ("rex-infernus","wardens-blight"),CZQ("rex-infernus")]],q:["r7"]}
 ],
 tips:["In co-op, extra Warden's Blights can come from the Mystery Box after the first is built.","Pack-a-Punch it immediately — the charged shot is mandatory later.","Walk backwards when the forging cutscene starts to skip the Warden's voice lines."]},

speedIntro:"The Veytharion and Caltheris temple puzzles can be done before the Wonder Weapon, and the Her House symbols take a few rounds to build. The speed route starts both early.",
steps:[
{id:"r1",t:"Pack-a-Punch",loc:"Her House → Nexus Forge",b:["Hold out in Her House. On round 3 answer the phone to open the front door.","<b>Before you leave,</b> shoot the basketball through the house's broken window — this starts the Her House symbols you need for the grapple upgrade.","Take the portal to the Nexus Forge and place the World Seed — two Dread Skulls fly off. Destroy them, take the Usurped Flame from Veytharion's and Caltheris' temples and throw each at a forge brazier.","Turn both crank wheels on the Nexus Forge; Pack-a-Punch opens."],ph:[["PaP",SK("6a8727b8add700.37077270")]]},
{id:"r2",t:"Astral Fire",loc:"Nexus Forge",b:["Take a Void Claw from a green pedestal. Grapple a floating purple orb toward PaP repeatedly; when it spins around the machine, turn the PaP crank. Braziers now give Astral Flame."]},
{id:"r3",t:"Veytharion stone blocks",loc:"Veytharion's temple",b:["Four blocks (Death Perception helps): <b>Water</b> — Sanctuary under the green lantern; <b>Fire</b> — Main Chamber upper ledge by the GobbleGum machine; <b>Earth</b> (plant) — upper ledge in the Mule Kick room; <b>Air</b> (hand) — lower Mule Kick room by the spawn window.","Ferry them across on the small platform and slot them into the left wall. Fire can never be left alone with Water or Earth — Air is the buffer.","Reward: the wall opens with the rain well/portal and a free perk."],ph:[["Blocks",SK("6a8bf918620653.88859748")]]},
{id:"r4",t:"Caltheris pressure plates",loc:"Caltheris' Main Chamber · downstairs",b:["Stand on the four floor squares from left to right; each reveals glowing lights on the walls/ceiling — shoot all four before the plate drops. Failed plates retry next round.","A wall opens with a Lantern and two more purple orbs."]},
{id:"r5",t:"Nyxara crystal and beam",loc:"Dravakar Main Chamber → Nyxara's temple",b:["Break the wall on the upper-right ledge above Dravakar's entrance; take the hidden Fracture to the holder in Nyxara's Main Chamber.","Throw Astral Flame at the big eye at the back. Grapple-rotate the Fractures until the beam melts the marked door into Nyxara's Inner Sanctum."]},
{id:"r6",t:"The Forest → three parts",loc:"Nyxara's Inner Sanctum",gate:"Round 8+",b:["Let the vine drain your health until its bar fills; eat the fruit (round 8+).","Parts: charred body by the central rock, charred body at the cave entrance, and melee the floorboards in the burned cabin. Ejected early? Return next round."]},
{id:"r7",t:"Dravakar's riddle → forge Warden's Blight",loc:"Dravakar's chamber",b:["Read the blue writing, set the Left, Bottom and Right switches per the riddle (Codes tab), pull the center lever. The ceiling opens.","Grapple up in Dravakar's Secret Passage into the Forge Room and use the anvil. Pack-a-Punch the Blight."],ph:[["Blight",SK("6a876707c67548.89165286")]]},
{id:"r8",t:"Her House symbols",loc:"Nexus Forge, looking at Her House",b:["If you didn't shoot the basketball before leaving the house, shoot the tiny basketball above the broken right-side window (scoped weapon helps).","Over the next 3–4 rounds four blue symbols appear on the house. Record the order, oldest to newest. Don't shoot them yet."]},
{id:"r9",t:"Special exfil → Eye of the Forge",loc:"Exfil round (11, 16, 21…)",gate:"Exfil round",b:["Shoot the four symbols in order; the Twins dance. Answer the Nexus Forge exfil phone, kill the HVT, take the portal into Her House (the Twins give a PaP crystal if your Blight isn't upgraded).","Upstairs, fire a fully charged Blight shot at the zombie spawn by the bed for the Eye of the Forge (Skycoach shows the upstairs toilet instead — try it if the bed spawn doesn't work). Survive until the phone rings and portal out."]},
{id:"r10",t:"Void Talon",loc:"Green grapple pedestal",b:["Empower the Eye at a grapple station — your Void Claw becomes the red Void Talon."],ph:[["Talon",SK("6a8bfaa12ce183.97799894")]]},
{id:"r11",t:"Rebuild the Nexus",loc:"Nexus Forge + Nexus Core",b:["Pull purple orbs to PaP and crank to surge the Nexus (lights the braziers).","Rip off 15 eye plates with the Talon: 12 in the Nexus Core and 3 on the Monoliths.","Kill the Deathspinners and burn the webs off the gears (fireball, explosive or a Blight charge).","Crank the Pack-a-Punch well wheel, sprint down and pull the lever before it stops. The Monolith cranks now aim beams at the temples (the lever under PaP sets the crank direction)."],ph:[["Nexus",SK("6a8bfb00c61465.55395623")]]},
{id:"r12",t:"Corruption items",loc:"Around the map",b:["<b>Caltheris — Shimmering Thread:</b> pull in purple orbs with the Void Claw and interact until one drops it.","<b>Nyxara — Ancient Scroll:</b> put Shadow Rift on your gun and get kills in the Forest until a falling zombie drops it.","<b>Dravakar — Blacksmith's Hammer:</b> put Shatter Blast on your gun and kill zombies near the Viking shield in the Wonder Weapon Forge Room until it breaks.","<b>Veytharion — Woven Sash:</b> needs rain (use the well). It floats out of bounds in one of three spots: right of the Mystery Box behind PhD, left of Juggernog, or by Widow's Wine heading toward Veytharion's temple. Grapple out and grab it."]},
{id:"r13",t:"Cleanse Nyxara",loc:"Nyxara",b:["Aim the Monoliths at her temple → Scroll in her brazier → Astral Flame → let a zombie take the flame and die at the matching hand of the Titan Trap near Veytharion.","Slab: go prone and stay still for about a minute. Raise the ring with a charged shot; aim the disc at the lower wall under her main area; fill the soul box.","Shoot her face, destroy the Shadow Souls, shoot the face again. Bring a purple orb under the floating platform below her head and charge-shoot to light the eyes. Flip to a rain round and throw Astral Flame at the point between her eyes."],ph:[["Nyxara",SK("6a8bfbc453cfe9.75298519")]]},
{id:"r14",t:"Cleanse Dravakar",loc:"Dravakar",b:["Hammer in his brazier → Titan Trap near Caltheris.","Slab: stand on it and get kills; if you step off, get back on the slab to continue. Aim the disc at the back-right wall.","Shadow Souls sit high (ceiling, above the entrance). Rain-round flame at his forehead above the eye."]},
{id:"r15",t:"Cleanse Caltheris",loc:"Caltheris",b:["Thread in his brazier → Titan Trap near Caltheris.","Slab: stand still aiming down sights (face the Mystery Box). Disc at the middle-left wall. Rain-round flame between the eyes."]},
{id:"r16",t:"Cleanse Veytharion",loc:"Veytharion",b:["Sash in his brazier → Titan Trap in front of Veytharion.","Slab: keep jumping on it for about a minute. Disc into the lower-left zombie spawn window. Rain-round flame at the forehead."]},
{id:"r17",t:"Boss: The Warden",loc:"Nexus Core circles",b:["Everyone stands on a glowing circle, then interact in the center. Bring PaP III Blight, a PaP III long-range gun, self-revive, Kazimirs and spare essence.","Phase 1: break the orbiting skulls, then hit the glowing scorpion tail while he's stunned.","Phase 2: he adds Warden Stingers and an AOE portal — clear them while you keep breaking skulls. Too many Stingers charge an attack that downs everyone.","Phase 3: you're pulled into Clausura for a trial (a different one per player in co-op). He seems to die, then returns for a final phase — same loop."],ph:[["Warden",SK("6a8bfc22474e59.32822099")]]}
],
speed:["r1","r8","r2","r3","r4","r5","r6","r7","r12","r9","r10","r11","r13","r14","r15","r16","r17"],
speedNotes:{r1:"Shooting the basketball before you leave the house starts the symbol timer right away.",r8:"The four symbols build up while you do everything else, ready for the round 11 exfil.",r3:"Doable before the Wonder Weapon. Use the well later for the Sash rain round.",r4:"Also doable early; the Lantern refills purple orbs you'll burn through.",r12:"Collect the Thread, Scroll and Hammer while you wait for an exfil round."},

side:[
{t:"Free power-up statues",r:"8 free power-ups, then a free perk",b:["Shoot each icon:","<b>Max Ammo:</b> behind the painting in Her House.","<b>Insta-Kill:</b> Nyxara's temple, through a floor crack near a Shadow Soul spawn.","<b>Full Power:</b> near the top of Veytharion's temple, by the pillar at the front door.","<b>Max Armor:</b> Dravakar's temple, first zombie window on the left.","<b>Bonus Points:</b> near Stamin-Up, outside the map at a temple.","<b>Nuke:</b> on a ledge between Caltheris and Dravakar.","<b>Double Points:</b> behind the spawn house — stand near Caltheris' temple, up on the rock.","<b>Fire Sale:</b> behind the Mystery Box on the Juggernog island, inside the third opening of the short building.","<b>Free perk:</b> on the bridge leading from the Coliseum (after the others)."]},
{t:"Veytharion vault",r:"Free random perk + the rain well",b:["Finish the Veytharion stone-block puzzle (main quest step) — the wall opens."]},
{t:"Mister Peeks Dance Party",r:"Perks, tools and loot (scales with your score) + calling card; repeatable",req:"Void Claw",b:["Pull purple orbs into the bone-pile dig sites and dig until a cassette tape drops.","Play it in the tape player near Widow's Wine (upper wall of Aranea Insula) and hit the dance prompts."]},
{t:"Mister Peeks Parkour",r:"Loot each clear; clear it twice for a mask (the astronaut / Space Mask: no fall damage, longer grapples)",req:"Every door open (except for the head)",b:["Collect six Peeks parts:","<b>Head:</b> nightstand behind you when you spawn in the house.","<b>Caltheris Passage:</b> floating out of bounds, right of the bridge.","<b>Ruinas Insula:</b> look down from the Mystery Box platform toward the big rock formation.","<b>Aranea Insula:</b> floating along the rock wall near the abyss by the exfil booth.","<b>Spira Insula:</b> seen from the platform floating above Juggernog.","<b>Nexus Forge:</b> near a grapple point between the Dravakar and Veytharion temples.","Go upstairs in Caltheris' temple, talk to Peeks and grapple through the rings as fast as you can (under 60 s)."]},
{t:"Warden Hat",r:"Hat that makes you immune to web slow",req:"Round 16+",b:["Ride a Web Mother inside the Nexus near Pack-a-Punch and get kills (kills count per Web Mother, so reuse the same one).","It kicks you off and jumps into Pack-a-Punch, dropping the hat."]},
{t:"Her House basement",r:"Two rewards, then a mask on the third",req:"Round 11+",b:["Survive in the house to at least round 11. Melee behind the painting to open the way downstairs.","Rewards spawn — the third is always a mask. You can't answer the phone while waiting."]},
{t:"Forest toy box",r:"A mask after each mini-game is cleared twice",b:["Find the Paradox Junction toy box inside the Forest. It spawns three items, each starting a different mini-game. Play each one twice."]},
{t:"Corrupted FAL / Corrupted Olympia",r:"A corrupted wonder-tier version of the Novaline (FAL) or M10 Breacher (Olympia) — one per match",b:["Buy the Novaline or the M10 Breacher off the wall.","Pack-a-Punch three times. On the next spider round, the gun glows.","Hit it with Astral Flame to spawn an HVT Web Mother; kill it for the corrupted gun.","It hurts you while you hold it. PaP stops that, but each bullet then drains health instead — it can drop you to 1 HP but can't kill you."]},
{t:"Song: “All We Are”",r:"Music (Kevin Sherwood & Elena Siegman)",b:["Headset 1: in Nyxara's temple — wall-jump or grapple up.","Headset 2: on a ledge by PhD Flopper.","Headset 3: behind the GobbleGum machine by Widow's Wine."]}
],

relicNote:"Rex Infernus has no relics of its own. Relics from the other five maps all work here.",
relics:[],

intel:[
{k:"Audio log",n:"The Long Game",a:"Nyxara's Temple",loc:"Sanctuary, right of the Arsenal"},
{k:"Audio log",n:"Pecking Order",a:"Veytharion's Temple",loc:"Sanctuary, on a pile of rocks"},
{k:"Audio log",n:"A Game of Cat and Strauss",a:"Her House",loc:"Play the piano: 8-6-7-5-6-5-3-5-4"},
{k:"Audio log",n:"The Mark",a:"Caltheris' Temple",loc:"Sanctuary, on the floor left of the door"},
{k:"Audio log",n:"Spa Day",a:"Dravakar's Temple",loc:"Sanctuary, up the stairs on a ledge"},
{k:"Document",n:"The First to Fall",a:"Spira Insula",loc:"On a floating rock above the ammo crate near Juggernog"},
{k:"Document",n:"The Others That Followed",a:"Aranea Insula",loc:"Left of the GobbleGum machine near Widow's Wine, under webs"},
{k:"Document",n:"The Inevitable End",a:"Ruinas Insula",loc:"Above the door from PhD to Dravakar's Sanctuary"},
{k:"Document",n:"Longterm Goals",a:"Nexus Forge",loc:"Keep digging up the dig sites around the map"},
{k:"Document",n:"Blueprint",a:"Her House",loc:"Play the piano: 8-6-7-5-6-5-3-5-4"},
{k:"Document",n:"Squish",a:"Her House",loc:"Jump on the bed in the children's room five times"},
{k:"Artifact",n:"World Seed",a:"Nexus Forge",loc:"Turn on Pack-a-Punch"},
{k:"Artifact",n:"Void Claw",a:"Nexus Forge",loc:"Grab a grapple after Pack-a-Punch"},
{k:"Artifact",n:"Warden's Blight",a:"Dravakar's Temple",loc:"Build the Wonder Weapon"}
],

areas:["Her House","Nexus Forge","Nexus Core","Veytharion's Temple","Caltheris' Temple","Dravakar's Temple","Nyxara's Temple","The Forest","Spira Insula","Aranea Insula","Ruinas Insula","Coliseum & bridges"],
pins:[
{a:"Her House",c:"quest",n:"Phone / basketball / symbols",d:"Round 3 phone; basketball through the window."},
{a:"Her House",c:"quest",n:"Upstairs bed spawn",d:"Eye of the Forge (charged Blight)."},
{a:"Her House",c:"egg",n:"Painting / basement",d:"Round 11+ mask rewards."},
{a:"Her House",c:"pu",n:"Max Ammo",d:"Behind the painting."},
{a:"Her House",c:"egg",n:"Peeks head + piano",d:"Nightstand; piano code 8-6-7-5-6-5-3-5-4."},
{a:"Nexus Forge",c:"quest",n:"Braziers / PaP cranks",d:"Usurped Flames, Astral Fire."},
{a:"Nexus Forge",c:"tool",n:"Void Claw pedestals",d:"Green grapple stations."},
{a:"Nexus Forge",c:"egg",n:"Peeks part (Nexus)",d:"Grapple point between Dravakar and Veytharion."},
{a:"Nexus Core",c:"quest",n:"Eye plates / gears / boss circles",d:"Rebuild the Nexus; start the Warden."},
{a:"Nexus Core",c:"egg",n:"Web Mother → PaP",d:"Warden Hat."},
{a:"Veytharion's Temple",c:"quest",n:"Stone blocks",d:"Fire / Water / Earth / Air."},
{a:"Veytharion's Temple",c:"perk",n:"Vault perk + well",d:"After the blocks."},
{a:"Veytharion's Temple",c:"pu",n:"Full Power",d:"Top, by the front-door pillar."},
{a:"Caltheris' Temple",c:"quest",n:"Pressure plates",d:"Lantern + purple orbs."},
{a:"Caltheris' Temple",c:"egg",n:"Peeks parkour start",d:"Upstairs."},
{a:"Dravakar's Temple",c:"ww",n:"Switch riddle / Forge Room",d:"Anvil and Viking shield (Hammer)."},
{a:"Dravakar's Temple",c:"pu",n:"Max Armor",d:"First zombie window on the left."},
{a:"Nyxara's Temple",c:"ww",n:"Eye + Fractures",d:"Beam to the Inner Sanctum door."},
{a:"Nyxara's Temple",c:"music",n:"Headset 1",d:"Wall-jump or grapple up."},
{a:"Nyxara's Temple",c:"pu",n:"Insta-Kill",d:"Through a floor crack."},
{a:"The Forest",c:"ww",n:"Three Blight parts",d:"Rock body, cave body, cabin floorboards."},
{a:"The Forest",c:"egg",n:"Paradox Junction toy box",d:"Three mini-games."},
{a:"Spira Insula",c:"pu",n:"Fire Sale",d:"Behind the Mystery Box, short building."},
{a:"Spira Insula",c:"quest",n:"Horse (shoes)",d:"Super EE — high above Juggernog."},
{a:"Aranea Insula",c:"egg",n:"Tape player",d:"Dance Party."},
{a:"Aranea Insula",c:"music",n:"Headset 3",d:"Behind GobbleGum by Widow's Wine."},
{a:"Ruinas Insula",c:"music",n:"Headset 2",d:"Ledge by PhD."},
{a:"Coliseum & bridges",c:"perk",n:"Free perk icon",d:"Bridge from the Coliseum."},
{a:"Coliseum & bridges",c:"quest",n:"Grapple lock",d:"Under the bridge in Nyxara's Passage — Super EE."}
],

toy:{name:"Warden (final toy)",prep:"Collect and exfil with the other five toys first. Get Warden's Blight, do the Her House eye step and have the Void Talon.",
 steps:[["Hidden grapple lock","Under the bridge in Nyxara's Passage, find the floating lock and grapple it. ~90 s rock-parkour course up to Her House; a fall sends you back (retry next round).",[["Lock",SK("6ab2932b13a285.02322380")]]],
  ["Bring the toy box in","At the end, stand on the ghostly toy box until it tips you both onto Her House. Activate Aether Shroud and interact — it becomes real and three toy horses appear.",[["Box",SK("6ab293398165d9.83033750")]]],
  ["Three horses","High above the Juggernog, Widow's Wine and PhD Flopper islands. Grapple up and melee each mid-air. They drop shoes, skates and a jumprope (ghostly).",[["Horses",SK("6ab2934c92b144.97861894")]]],
  ["Three soul challenges","Shoes (Juggernog): kills while jumping. Skates (Widow's Wine): PhD Flopper kills. Jumprope (PhD): Frenzied Guard kills. Each turns solid when done.",[]],
  ["Her House","On the next exfil round DON'T use the booth — take the portal at the Nexus Forge to Her House. Put the three items in the toy box for the Warden toy, then interact with the upstairs toy shelf to start the playdate. Each player must place their own Warden for rewards.",[["Portal",SK("6ab2935ee208a7.86948636")],["Shelf",SK("6ab2936aad8a73.41544439")]]]]},
codes:"rex",
src:[["MargwaNetwork — Rex Infernus","https://margwa.net/rex-infernus"],["BO7 Easter Eggs (Google Doc)","https://docs.google.com/document/u/0/d/1zFsG8A0BA_jUt8BNoAd2lmw36OR35ecOzicHwoXsexw/mobilebasic"],["Skycoach — main quest","https://skycoach.gg/blog/call-of-duty/articles/rex-infernus-easter-egg-guide"],["Skycoach — Super EE","https://skycoach.gg/blog/call-of-duty/articles/super-easter-egg-guide"]]
});
