MAPS.push({
id:"toten", slug:"totenreich", name:"Totenreich", color:"#3d8fd6", season:"Season 3 Reloaded", date:"Apr 30, 2026",
blurb:"Eidskallen, a Norse fishing town ripped into the Dark Aether after Group 935's experiments. Blizzards slow you down, and a giant robot named Tyr watches over the island.",
ww:"Jotunn Star", boss:"Dravakar", reward:"“Ambition” Richtofen skin + calling card",
mapImg: MGMAP("totenreich"),

wwInfo:{what:"A lantern-topped weapon with a melee attack, a charged ranged shot (charge it with melee kills) and a lantern that protects you and teammates from freezing.",
 steps:["<b>Chain Links:</b> in the Dry Dock Titan Crane room press Engage, wall-jump on the lowered wall and hold interact mid-jump to grab the links off the ship's nose.","<b>Chilly Chunks:</b> crate of seal-meat cans by the truck on Storm Bridge.","Open the double doors in the Burial Grounds (behind the Stave Church) with the Chain Links.","Put the Chilly Chunks on the Skallen Market trolley. On the <b>second</b> special round (about round 10) the bear Varkrith spawns — kill it for the Lantern.","Put the Lantern on the Burial Grounds table and solve the constellation order (left, right, back, front).","Follow Astrid through her soul boxes and the floating parkour route to the Lighthouse; take the Jotunn Star from the table inside."],
 tips:["Pack-a-Punching the Jotunn Star makes the boss's floating heads much easier.","If you want the Dancing Arnie relic, use the first Chilly Chunks for it before you bait the bear — grab another can afterwards."]},

speedIntro:"Most of Totenreich's middle section (three uranium pieces) can be done in any order. The speed route grabs every early freebie and baits the bear straight away so the special-round wait overlaps other work.",
steps:[
{id:"t1",t:"Power and Pack-a-Punch",loc:"Eidskallen Landing → Core Foundry → Skallen Market → Tyr's Head",b:["Follow the markers. Repair the power boxes in the Core Foundry and Skallen Market, then enter Tyr's Head and use the computer.","Leave by teleporter, take the Admin keycard from the Dry Dock, open the War Factory admin door, take the Glocke Drop Controller.","Sync it at the pulsing spot on Fishery Island for a minute. Pack-a-Punch drops from the sky — and you can call it anywhere while holding the controller."],ph:[["Spawn",SK("69f3bce962eaf1.88975457")],["Box 1",SK("69f3bcf87d7f40.97223867")],["Box 2",SK("69f3bd1b19ef02.39239253")],["Tyr's Head",SK("69f3bd2f4f33c6.89499970")]]},
{id:"t2",t:"Chain Links",loc:"Dry Dock · Titan Crane",b:["Press Engage, wall-jump on the lowered crane wall and hold interact mid-jump to grab the links on the ship's nose."],ph:[["Crane",SK("69f3bd52ada451.21992265")]]},
{id:"t3",t:"Chilly Chunks",loc:"Storm Bridge",b:["Interact with the crate of seal-meat cans by the truck."],ph:[["Cans",SK("69f3bd7242b590.03797776")]]},
{id:"t4",t:"Open the Burial Grounds room",loc:"Behind the Stave Church",b:["Use the Chain Links on the double doors."]},
{id:"t5",t:"Bait the bear → Lantern",loc:"Skallen Market",gate:"2nd special round (~R10)",b:["Put the Chilly Chunks on the trolley (“for Frosty”). On the second special round Varkrith the bear spawns — kill it for the Lantern."],ph:[["Trolley",SK("69f3bd869d4762.61259447")]]},
{id:"t6",t:"Constellation puzzle",loc:"Burial Grounds room",b:["Place the Lantern. Stand with your back to the stairs and match the table's symbols to the wall projections in this order: left, right, back, front. A wrong pick resets it."]},
{id:"t7",t:"Astrid → Jotunn Star",loc:"→ Lighthouse",b:["Follow Astrid's soul boxes (ice zombies help fill them). Skip the zipline and take the floating parkour route to the Lighthouse, then climb and enter. Take the Jotunn Star."],ph:[["Astrid",SK("69f471d6742645.72777800")]]},
{id:"t8",t:"Wundersignal → Barrage Controller",loc:"Lighthouse → War Factory → Beacon Island → Tyr's Head → Core Foundry",b:["Crowbar on the Lighthouse <b>2nd floor</b>.","War Factory admin room: the cargo manifest's ammo-icon row gives a crate ID. The four bullet crates are: Core Foundry by the sniper wall-buy, behind the boat in the Dry Dock, the room before Admin in the War Factory, and the end of Fjord Road. Wrong crates can gas or EMP you. Take the Flak Gun Round.","Load the correct Beacon Island flak cannon and melee it with the Jotunn Star — it shoots the robot head by spawn. Interact twice there for salvage, then the Transmitter.","Install the Transmitter on the sparking panel in Tyr's Head. Count two pairs of left/right white-light flashes.","Molotov the frozen zipline rope in the Core Foundry, climb the broadcast tower and enter each pair on the oscilloscope dials. Take the Wonder Barrage Controller."],ph:[["Crowbar",SK("69f472e3a4fad9.11928114")],["Lights",SK("69f4758ec1b8c1.71181095")],["Rope",SK("69f475b20c3ab9.94290509")],["Dials",SK("69f475c925a745.98979248")]]},
{id:"t9",t:"Uranium 1: radioactive fish",loc:"Any fishing spot",b:["After you have the Jotunn Star, look for a green glow in the water. Fish it up with an Olaf's Cod Cranker rod (reel when the rod glows blue).","An irradiated Ravager appears — it becomes a Tac Map HVT next round. Damage it, follow it, repeat until it dies and drops uranium."]},
{id:"t10",t:"Uranium 2: Genetic Lab",loc:"Core Foundry → under Fishery Island",b:["Use an RC-XD (one is free on a crate in Eidskallen Square). Shoot the small metal grate in the Core Foundry, drive through, jump the water and detonate by the barrels.","In the lab, two door numbers have radiation symbols. Convert (1=A … 5=E) and put those two head jars on the machine — purple means right.","Use the purple jar on the crab claw for the Necro Spike, pick the three-pin cell lock, take the uranium."],ph:[["Lab",SK("69f47830cc07e1.92838224")],["Jars",SK("69f478a6e8ebe2.26271666")]]},
{id:"t11",t:"Uranium 3: Glocke Drop",loc:"Anywhere with a horde",b:["Call a Glocke Drop scorestreak on a big group. Shoot only the floating orange zombies until every side light is green; it drops the last uranium."]},
{id:"t12",t:"Atomkraft Core",loc:"Dry Dock → Machine Workshop",b:["Barrage the blocked stairs by the Dry Dock crafting table to open the Machine Workshop.","Load the uranium in the claw machine. Place rods so the meter lands in green: clustered rods add a lot, isolated rods add a little. Fail = next round."],ph:[["Workshop",SK("69f479a5e72385.01716987")],["Rods",SK("69f47ad1750cf9.44807526")],["Rods 2",SK("69f47b8739ab04.23527710")]]},
{id:"t13",t:"Charge the core → Dravakar Shard",loc:"Eidskallen Landing → Storm Bridge",b:["Walk it (no sprint, no ziplines, don't enter Tyr's Head) to the box by Quick Revive; run the generator in the nearby shack and defend, restarting it when it stalls.","Carry the charged core to the yellow-striped black barrel mid Storm Bridge (it drains health; ice walls rise). Watch the robot fight Dravakar, then grab the shard (also called the Vegvisir) near Tyr's Foot."]},
{id:"t14",t:"Sunstone",loc:"Blodheim Hall",b:["Put the shard on the fire pit in front of Vulture Aid. Charge the Jotunn Star with melee kills and shoot the shard to light a blue flame.","Use a Disciple Injection (a free one is in the Stave Church) and throw zombies into the fire until a lockdown starts. Kill the Necropincer HVT (Calrynnor) and pick up the Sunstone by the pit."],ph:[["Sunstone",SK("69f47d1a344831.61489490")]]},
{id:"t15",t:"Rune bonfires",loc:"Stave Church → around the map",b:["Place the Sunstone on the Church altar (the sundial podium) and melee it with the Jotunn Star. A rune dial appears above the roof: arrows with 1, 2, 3 lines point at three symbols.","Hit the matching bonfire mounds with charged shots in that order (Burial Grounds, Eidskallen Square, Lighthouse, spawn, bridge left side). Wrong one = the dial resets."],ph:[["Dial",SK("69f47d86b91220.19085431")]]},
{id:"t16",t:"Boss: Dravakar",loc:"Start from Tyr's Head front panel",b:["Shoot red weak spots; hide behind pillars from rocks and meteors; leave frozen zones.","When he's immune, knock down the floating Gjallarfrost heads with charged shots in the mouth (stand in a trap's bubble to fire freely), then break them for ammo and armor.","Final phase: shoot his face/eyes while weaving through S, V, arrow and low-line rock patterns (go prone under low lines)."],ph:[["Boss",SK("69f4832bc73ef1.79578741")]]}
],
speed:["t1","t2","t3","t5","t4","t6","t7","t11","t10","t9","t8","t12","t13","t14","t15","t16"],
speedNotes:{t1:"On your way through Eidskallen Square, take the free RC-XD and save it for uranium 2.",t3:"Grab the cans on the same trip as the chain links.",t5:"Bait the bear as soon as you have the cans — the Lantern waits on the second special round, so start the clock early.",t11:"Craft or fish a Glocke Drop while waiting; uranium order doesn't matter.",t8:"The Barrage Controller is only needed to open the Workshop, so gather the uranium first."},

side:[
{t:"Tyr's Power-Ups",r:"A random power-up, once per round (≈15 completions unlock the Cointoss Helm)",b:["Inside Tyr's Head, the lightbulbs above the robot's monitor show a grid coordinate and the number 75.","Get 75 kills while standing in that grid square on the Tac Map.","Tyr's Head flashes green and a random power-up spawns inside."]},
{t:"Power-up statues",r:"7 free power-ups, then a Fire Sale and a free random perk",b:["Shoot each statue:","<b>Bonus Points:</b> outside Beacon Island, between two wooden walls.","<b>Insta-Kill:</b> on a tombstone outside the Burial Grounds.","<b>Double Points:</b> under the finger of Tyr's left hand, off Storm Bridge.","<b>Nuke:</b> behind the Riese robot head in the War Factory.","<b>Full Power:</b> boat window inside the Dry Dock.","<b>Max Armor:</b> Lief's Boat Repair, behind a hanging basket in the top-left corner of the north entrance.","<b>Max Ammo:</b> Fishery Island, on the wooden structure left of Juggernog.","<b>Fire Sale</b> (after all seven): Eidskallen Square, second floor of the burning west building.","<b>Random Perk</b> (after all seven): spawn — directly behind where you start, through the window."]},
{t:"Fishing",r:"Essence, salvage, equipment and scorestreaks (repeatable)",b:["Take an Olaf's Cod Cranker rod from Blodheim Hall, the Dry Dock, Fishery Island, Storm Bridge or Beacon Island.","Cast at any of the 11 fishing spots (red on the minimap): Eidskallen Landing ×2, Eidskallen Square ×2, Dry Dock, Beacon Island ×2, Fishery Island ×2, Tyr's Foot, Tyr's Shoulder.","Reel when the rod glows blue. Sometimes you hook a boot that turns into a zombie."]},
{t:"Golden Tide Helm",r:"Blue helmet (fishing perks); rebuy free at Blodheim Hall",b:["Keep fishing with the Cod Cranker until Olaf, Cranker of Cod spawns wearing the helmet.","Kill him and pick it up."]},
{t:"Kneehigh Helm",r:"Orange gnome helmet; rebuy at Blodheim Hall for 6,000 essence",b:["Put Shadow Rift on your gun and shoot all four gnome statues:","1. Between two wooden sheets next to the Machine Workshop catwalk.","2. Next to a searchlight on a concrete building far outside Tyr's Foot.","3. Below the painting on the Stave Church altar.","4. On the Lighthouse's top catwalk — seen from the flak gun, facing away from the Lighthouse.","Pick the helmet up from the counter at Loven's Antiquities."]},
{t:"Cointoss Helm",r:"Yellow helmet — more frequent power-ups; rebuy free at Blodheim Hall",b:["Complete Tyr's Power-Ups about 15 times. The helmet appears inside Tyr's Head."]},
{t:"Icebane Helm",r:"White helmet — immune to freezing; rebuy free at Blodheim Hall",b:["Build the Flammenfalle trap. Get 250 trap kills, plus 50 Frost Zombie kills with a bullet weapon inside its area.","The helmet drops on the ground."]},
{t:"Fishy Fish Bot trap",r:"A buildable trap that lures zombies and Brain-Rots some of them",b:["Take the fish from the bucket on a shelf in the shed next to the Arsenal on Beacon Island.","Get a Shock Charge and wait for a T.E.D.D. Task. Put the fish on the T.E.D.D. machine, throw the Shock Charge at it and finish the task (max reward).","The fish drops with a machine piece. Take both to the mount across from the Arsenal in Eidskallen Square and hold interact to build it. Each use costs 2,000 essence."]},
{t:"Echoes of the Damned (Richtofen)",r:"Story scene with Von List; unlocks the Agarthan Device throne",req:"Melee Macchiato · round 15 or any round ending in 5 or 0",b:["Melee the barrel by the courtyard doorway in the Core Foundry and dig out the Iron Cross (Ritterkreuz).","Enter the three codes on the radio: <b>01 01 05</b>, <b>09 03 05</b>, <b>07 00 04</b>.","Enter the hidden throne room for the cutscene. Placing the three Agarthan Device items on the throne here unlocks that relic."]},
{t:"Silent Heir crossbow",r:"Hidden crossbow (needed for the Super EE)",b:["Lighthouse first floor: go prone near the broken edge above the GobbleGum machine for a hidden prompt."]},
{t:"Free early tools",r:"Free RC-XD and Disciple Injection",b:["RC-XD on a crate in Eidskallen Square; Disciple Injection in the Stave Church."]},
{t:"Song: “No One There”",r:"Music",b:["Headset 1: near PhD Flopper at the Dry Dock (crates on the side of the boat).","Headset 2: inside the Core Foundry, toward Double Tap.","Headset 3: bottom of a shelf by a plate in Loven's Antiquities."]}
],

relicNote:"Relics need this map's main quest done once. The Wrestler's Belt still has no known unlock.",
relics:[
{n:"Power Switch",tier:"grim",e:"Tactical and lethal equipment randomize every round.",trial:"Zombies can only be damaged by traps.",u:["Outside the map are four pyres with deer heads; count the skulls on each (1 to 4).","Match each pyre's map quadrant to a bear pelt in the Blodheim Hall mess hall.","Throw Combat Axes (tomahawks) at the pelts in order from 1 skull to 4. The portal spawns on a pelt. Possible from round 1."]},
{n:"Wrestler's Belt",tier:"grim",e:"Wall-buys randomize every round.",trial:"—",u:["<span class='unsolved'>Unsolved — no working method found yet.</span>"]},
{n:"Stuffed Elephant",tier:"sin",e:"Health regeneration is slowed.",trial:"Find 4 Mister Peeks eggs and kill the matching HVT in time (retry next round if you fail).",u:["Reach round 40 without buying perks. Free perks from T.E.D.D. trials, Mister Peeks, Melee Macchiato and PhD Flopper don't count."]},
{n:"Dancing Arnie",tier:"sin",e:"Perk machines give random Perk-a-Colas.",trial:"Melee damage only.",u:["Put a market cooking pot in the mess hall.","Add a pint of ale (near the antique shop), the Chilly Chunks (use your first can before the bear step), and a lobster from a Pincer killed with the Flammenfalle trap.","A Mister Peeks soul box spawns on the pot. Fill it with kills nearby; the portal appears."]},
{n:"Agarthan Device",tier:"wic",e:"A different zombie type spawns each round.",trial:"Zombies can only be damaged while you're inside (Tyr).",u:["Collect a walkie-talkie (jail cell), a stuffed Mister Peeks (under Ava's bed in the motel teleport room) and a Mangler helmet (Requiem teleport room).","Do the Echoes of the Damned side egg and place all three on the throne."]},
{n:"Music Box",tier:"wic",e:"Enemies only take critical damage.",trial:"Mister Peeks spawns in different areas — reach each within 30 seconds and kill enough zombies there.",u:["After round 60, get five headshot kills from inside Tyr's Head."]}
],

intel:[
{k:"Audio log",n:"Building Blocks",a:"Eidskallen Landing",loc:"On barrels across from the ammo crate around the corner from Quick Revive",ch:"Barrels of Fun"},
{k:"Audio log",n:"Limitations",a:"Genetic Lab",loc:"Next to the cages",ch:"Cage Match"},
{k:"Audio log",n:"The Chair Incident",a:"Eidskallen Landing",loc:"Next to the big silo",ch:"Holey Buckets"},
{k:"Audio log",n:"The Serpent's Head",a:"Eidskallen Square",loc:"On a boat behind the Arsenal building",ch:"All Ashore"},
{k:"Audio log",n:"Talk",a:"War Factory",loc:"On a console near the Arsenal",ch:"Control Issues"},
{k:"Audio log",n:"He Left Us",a:"Core Foundry",loc:"Table in the console room next to Double Tap",ch:"Mixed Signals"},
{k:"Audio log",n:"Problems",a:"Core Foundry",loc:"Echoes of the Damned side egg"},
{k:"Audio log",n:"Solutions",a:"Core Foundry",loc:"Echoes of the Damned side egg"},
{k:"Audio log",n:"Counting the Cost",a:"Core Foundry",loc:"Echoes of the Damned side egg"},
{k:"Document",n:"Little Fishes",a:"Skallen Market",loc:"Under a crate on a cart near the power line you repair",ch:"Craft Services"},
{k:"Document",n:"Saboteur",a:"Dry Dock",loc:"On a barrel next to the boat",ch:"Refueling"},
{k:"Document",n:"Rezoning",a:"Eidskallen Square",loc:"On a box by the bread at the map edge, near an ammo crate",ch:"Fresh Buns"},
{k:"Document",n:"Secret and Safe",a:"Eidskallen Square",loc:"Side of the building closest to the Arsenal",ch:"Another Round?"},
{k:"Document",n:"Beneath the Boards",a:"Fishery Island",loc:"Big red building, on a ledge outside an entrance you jump to",ch:"Over Packed"},
{k:"Document",n:"Priorities",a:"War Factory",loc:"Throw a grenade into the open vent above the stairs",ch:"Can I Vent?"},
{k:"Document",n:"Radio Operator",a:"Lighthouse",loc:"On a crate (during the Wonder Weapon quest)",ch:"Don't Stair"},
{k:"Document",n:"Tyr's Bell",a:"Lighthouse",loc:"Top of the Lighthouse (during the Wonder Weapon quest)",ch:"Lightkeeper"},
{k:"Document",n:"Dossier",a:"Core Foundry",loc:"Echoes of the Damned side egg"},
{k:"Document",n:"Report",a:"Core Foundry",loc:"Echoes of the Damned side egg"},
{k:"Document",n:"Telegram",a:"Core Foundry",loc:"Echoes of the Damned side egg"},
{k:"Artifact",n:"Anatomy Chart",a:"Genetic Lab",loc:"On a wall near the desk where you get the Necro Spike",ch:"Meat Locker"},
{k:"Artifact",n:"Blueprint",a:"War Factory",loc:"On a wall in the room above the VS Recon wall-buy",ch:"We Are All His Slaves"},
{k:"Artifact",n:"Ritterkreuz",a:"Core Foundry",loc:"Echoes of the Damned (dig up the Iron Cross)"},
{k:"Artifact",n:"Fishy Fish Bot",a:"Eidskallen Square",loc:"Build the Fishy Fish Bot trap"},
{k:"Artifact",n:"Jotunn Star",a:"Lighthouse",loc:"Main quest — Wonder Weapon"}
],

areas:["Eidskallen Landing","Eidskallen Square","Stave Church & Burial Grounds","Skallen Market","Blodheim Hall","Core Foundry","War Factory","Genetic Lab","Dry Dock","Fishery Island","Beacon Island","Storm Bridge","Lighthouse","Tyr's Head"],
pins:[
{a:"Eidskallen Landing",c:"quest",n:"Core charging generator",d:"Box by Quick Revive + shack generator."},
{a:"Eidskallen Landing",c:"perk",n:"Random perk statue",d:"Behind spawn through the window (after the other statues)."},
{a:"Eidskallen Square",c:"tool",n:"Free RC-XD",d:"On a crate."},
{a:"Eidskallen Square",c:"egg",n:"Fishy Fish Bot mount / Loven's Antiquities",d:"Mount across from the Arsenal; Kneehigh Helm on the shop counter."},
{a:"Eidskallen Square",c:"music",n:"Headset 3",d:"Bottom shelf by a plate in Loven's Antiquities."},
{a:"Eidskallen Square",c:"pu",n:"Fire Sale statue",d:"2nd floor of the burning west building."},
{a:"Eidskallen Square",c:"quest",n:"Super EE iceberg",d:"Dock behind Ms Loven's Antique Shop."},
{a:"Stave Church & Burial Grounds",c:"ww",n:"Burial Grounds room",d:"Chain-link doors; Lantern constellation table."},
{a:"Stave Church & Burial Grounds",c:"quest",n:"Sundial altar",d:"Sunstone + rune dial."},
{a:"Stave Church & Burial Grounds",c:"tool",n:"Free Disciple Injection",d:"Inside the church."},
{a:"Stave Church & Burial Grounds",c:"pu",n:"Insta-Kill statue",d:"Tombstone outside the Burial Grounds."},
{a:"Skallen Market",c:"ww",n:"Bear trolley",d:"Chilly Chunks bait."},
{a:"Blodheim Hall",c:"quest",n:"Fire pit (Vulture Aid)",d:"Shard → blue flame → Sunstone."},
{a:"Blodheim Hall",c:"relic",n:"Bear pelts / cooking pot",d:"Power Switch axes; Dancing Arnie pot."},
{a:"Blodheim Hall",c:"egg",n:"Helmet rack",d:"Rebuy unlocked helmets; fishing rod."},
{a:"Core Foundry",c:"quest",n:"Grate & broadcast tower",d:"RC-XD grate; frozen zipline + dials."},
{a:"Core Foundry",c:"egg",n:"Richtofen barrel + radio",d:"Iron Cross and codes."},
{a:"Core Foundry",c:"music",n:"Headset 2",d:"Toward Double Tap."},
{a:"War Factory",c:"quest",n:"Admin room / manifest",d:"Glocke controller; crate ID."},
{a:"War Factory",c:"pu",n:"Nuke statue",d:"Behind the Riese robot head."},
{a:"Genetic Lab",c:"quest",n:"Head jars + cell lock",d:"Uranium 2."},
{a:"Dry Dock",c:"ww",n:"Titan Crane",d:"Chain Links."},
{a:"Dry Dock",c:"quest",n:"Machine Workshop",d:"Atomkraft rod puzzle."},
{a:"Dry Dock",c:"music",n:"Headset 1",d:"Boat crates by PhD Flopper."},
{a:"Dry Dock",c:"pu",n:"Full Power statue",d:"Boat window."},
{a:"Fishery Island",c:"quest",n:"Glocke sync spot",d:"Pack-a-Punch drop."},
{a:"Fishery Island",c:"pu",n:"Max Ammo statue",d:"Wooden structure left of Juggernog."},
{a:"Beacon Island",c:"quest",n:"Flak cannons",d:"Load the right one."},
{a:"Beacon Island",c:"egg",n:"Fish bucket",d:"Shed by the Arsenal — Fish Bot trap."},
{a:"Beacon Island",c:"pu",n:"Bonus Points statue",d:"Between two wooden walls outside."},
{a:"Storm Bridge",c:"ww",n:"Chilly Chunks crate",d:"By the truck."},
{a:"Storm Bridge",c:"quest",n:"Yellow-striped barrel",d:"Charged core → Dravakar shard."},
{a:"Storm Bridge",c:"pu",n:"Double Points statue",d:"Under the finger of Tyr's left hand."},
{a:"Lighthouse",c:"ww",n:"Jotunn Star table",d:"End of Astrid's route."},
{a:"Lighthouse",c:"tool",n:"Crowbar / Silent Heir",d:"Crowbar 2nd floor; crossbow prone on 1st floor."},
{a:"Tyr's Head",c:"egg",n:"Tyr's Power-Ups bulbs",d:"Coordinate + 75 kills."},
{a:"Tyr's Head",c:"quest",n:"Sparking panel / boss start",d:"Transmitter lights; front panel starts the boss."}
],

toy:{name:"Guardian",prep:"Equip Wildfire and pick up an Olaf's Cod Cranker fishing rod.",
 steps:[["Hook the iceberg","Behind Ms Loven's Antique Shop (Eidskallen Square dock), place the rod at the fishing spot, then pop Wildfire so the rod burns. Wait for the line to move, then reel (too early can soft-lock). Melt the iceberg with fire to reveal the toy box.",[]],
  ["Silent Heir","Reach the Lighthouse, go prone by the broken edge on the first floor (above the GobbleGum machine) and take the crossbow. Upgrade it.",[["Silent Heir",SK("6ab292b6683d55.28282764")]]],
  ["King Draugvald","He appears outside the map near the graves by the Wonder Weapon room and follows you. He regenerates if you stop damaging him. Any gun can weaken him, but the Silent Heir must land the kill. Wrong kill = he returns next round.",[["Draugvald",SK("6ab292c681c218.98117483")],["Crown",SK("6ab292e7919318.86250972")]]],
  ["Claim and exfil","Put his crown in the toy box for loot and the Guardian toy, then exfil.",[]]]},
codes:"toten",
src:[["MargwaNetwork — Totenreich","https://margwa.net/totenreich"],["BO7 Easter Eggs (Google Doc)","https://docs.google.com/document/u/0/d/1zFsG8A0BA_jUt8BNoAd2lmw36OR35ecOzicHwoXsexw/mobilebasic"],["Skycoach — main quest","https://skycoach.gg/blog/call-of-duty/articles/totenreich-easter-egg-guide"],["Skycoach — Super EE","https://skycoach.gg/blog/call-of-duty/articles/super-easter-egg-guide"]]
});
